IF (EXISTS (SELECT *  FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'CenaPoziomu'))
BEGIN
   DROP TABLE [dbo].CenaPoziomu;
END

CREATE TABLE [dbo].[CenaPoziomu](
	[Id] [bigint] NOT NULL,
	[ProduktId] [bigint] NOT NULL,
	[PoziomId] [int] NOT NULL,
	[Netto] [decimal](10, 2) NOT NULL CONSTRAINT [DF_ceny_poziomy_netto]  DEFAULT ((0)),
	[WalutaId] [bigint] NULL,
 CONSTRAINT [PK_ceny_poziomy] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_ceny_poziomy] UNIQUE NONCLUSTERED 
(
	[ProduktId] ASC,
	[PoziomId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]