//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolEx.Hurt.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KULEROS-PC\\SQLSERVER2008;Initial Catalog=SolEx_Hurt;Integrated Securi" +
            "ty=True")]
        public string SolEx_HurtConnectionString {
            get {
                return ((string)(this["SolEx_HurtConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KULEROS-PC\\SQLSERVER2008;Initial Catalog=B2BAmpbike;Integrated Securi" +
            "ty=True")]
        public string B2BAmpbikeConnectionString {
            get {
                return ((string)(this["B2BAmpbikeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex.net.pl;Initial Catalog=b2b-ampbike2;Integrated Security=True")]
        public string b2b_ampbike2ConnectionString {
            get {
                return ((string)(this["b2b_ampbike2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANNAKOMP;Initial Catalog=b2b-kolter;Integrated Security=True")]
        public string b2b_kolterConnectionString {
            get {
                return ((string)(this["b2b_kolterConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=annakomp;Initial Catalog=b2b-radom;Integrated Security=True")]
        public string b2b_radomConnectionString {
            get {
                return ((string)(this["b2b_radomConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex.net.pl;Initial Catalog=b2b-kolter;Integrated Security=True")]
        public string b2b_kolterConnectionString1 {
            get {
                return ((string)(this["b2b_kolterConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex.net.pl;Initial Catalog=b2b-print;Integrated Security=True")]
        public string b2b_printConnectionString {
            get {
                return ((string)(this["b2b_printConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex.net.pl;Initial Catalog=b2b-allgame;Integrated Security=True")]
        public string b2b_allgameConnectionString {
            get {
                return ((string)(this["b2b_allgameConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kuleros-pc\\sqlserver2008;Initial Catalog=b2b-borbet;Integrated Securi" +
            "ty=True")]
        public string b2b_borbetConnectionString {
            get {
                return ((string)(this["b2b_borbetConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex.net.pl;Initial Catalog=b2b-tekstylia;Integrated Security=True")]
        public string b2b_tekstyliaConnectionString {
            get {
                return ((string)(this["b2b_tekstyliaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex.net.pl;Initial Catalog=b2b-borbet;Integrated Security=True")]
        public string b2b_borbetConnectionString1 {
            get {
                return ((string)(this["b2b_borbetConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex.net.pl;Initial Catalog=b2b-exec;Integrated Security=True")]
        public string b2b_execConnectionString {
            get {
                return ((string)(this["b2b_execConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex.net.pl;Initial Catalog=b2b-exec2;Integrated Security=True")]
        public string b2b_exec2ConnectionString {
            get {
                return ((string)(this["b2b_exec2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex.net.pl;Initial Catalog=b2b-opoczno;Integrated Security=True")]
        public string b2b_opocznoConnectionString {
            get {
                return ((string)(this["b2b_opocznoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANNAKOMP;Initial Catalog=b2b-opoczno;Integrated Security=True")]
        public string b2b_opocznoConnectionString1 {
            get {
                return ((string)(this["b2b_opocznoConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex.net.pl;Initial Catalog=b2b-norma;Integrated Security=True")]
        public string b2b_normaConnectionString {
            get {
                return ((string)(this["b2b_normaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex.net.pl;Initial Catalog=b2b-partybox;Integrated Security=True")]
        public string b2b_partyboxConnectionString {
            get {
                return ((string)(this["b2b_partyboxConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex.net.pl;Initial Catalog=b2b-tenzo3;Integrated Security=True")]
        public string b2b_tenzo3ConnectionString {
            get {
                return ((string)(this["b2b_tenzo3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex.net.pl;Initial Catalog=b2b-print3;Integrated Security=True")]
        public string b2b_print3ConnectionString {
            get {
                return ((string)(this["b2b_print3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=178.33.51.128;Initial Catalog=b2b-essa;Integrated Security=True")]
        public string b2b_essaConnectionString {
            get {
                return ((string)(this["b2b_essaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=178.33.51.128;Initial Catalog=b2b-spragnieni3;Integrated Security=Tru" +
            "e")]
        public string b2b_spragnieni3ConnectionString {
            get {
                return ((string)(this["b2b_spragnieni3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=annakomp;Initial Catalog=b2b-essa;Integrated Security=True")]
        public string b2b_essaConnectionString1 {
            get {
                return ((string)(this["b2b_essaConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-print3;Integrated Security=True")]
        public string b2b_print3ConnectionString1 {
            get {
                return ((string)(this["b2b_print3ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-essa;Integrated Security=True")]
        public string b2b_essaConnectionString2 {
            get {
                return ((string)(this["b2b_essaConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex;Initial Catalog=b2b-tenzo;Integrated Security=True")]
        public string b2b_tenzoConnectionString {
            get {
                return ((string)(this["b2b_tenzoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-trojka;Integrated Security=True")]
        public string b2b_trojkaConnectionString {
            get {
                return ((string)(this["b2b_trojkaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=178.33.51.128;Initial Catalog=b2b-megima;Integrated Security=True")]
        public string b2b_megimaConnectionString {
            get {
                return ((string)(this["b2b_megimaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-megima;Integrated Security=True")]
        public string b2b_megimaConnectionString1 {
            get {
                return ((string)(this["b2b_megimaConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=178.33.51.128;Initial Catalog=b2b-ak;Integrated Security=True")]
        public string b2b_akConnectionString {
            get {
                return ((string)(this["b2b_akConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex;Initial Catalog=b2b-megima;Integrated Security=True")]
        public string b2b_megimaConnectionString2 {
            get {
                return ((string)(this["b2b_megimaConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=annakomp;Initial Catalog=b2b-megima;Integrated Security=True")]
        public string b2b_megimaConnectionString3 {
            get {
                return ((string)(this["b2b_megimaConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-ampbike;Integrated Security=True")]
        public string b2b_ampbikeConnectionString {
            get {
                return ((string)(this["b2b_ampbikeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=annakomp;Initial Catalog=B2B-ESSA2;Integrated Security=True")]
        public string B2B_ESSA2ConnectionString {
            get {
                return ((string)(this["B2B_ESSA2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex;Initial Catalog=b2b-ampbike2;Integrated Security=True")]
        public string b2b_ampbike2ConnectionString1 {
            get {
                return ((string)(this["b2b_ampbike2ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-techmet;Integrated Security=True")]
        public string b2b_techmetConnectionString {
            get {
                return ((string)(this["b2b_techmetConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-monk;Integrated Security=True")]
        public string b2b_monkConnectionString {
            get {
                return ((string)(this["b2b_monkConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-variant;Integrated Security=True")]
        public string b2b_variantConnectionString {
            get {
                return ((string)(this["b2b_variantConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-global;Integrated Security=True")]
        public string b2b_globalConnectionString {
            get {
                return ((string)(this["b2b_globalConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=87.204.181.7\\gb;Initial Catalog=b2b-global;User ID=gb_user;Password=G" +
            "B123baza")]
        public string b2b_globalConnectionString1 {
            get {
                return ((string)(this["b2b_globalConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-bioplanet2;Integrated Security=Tru" +
            "e")]
        public string b2b_bioplanet2ConnectionString {
            get {
                return ((string)(this["b2b_bioplanet2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-forcetop2;Integrated Security=True" +
            "")]
        public string b2b_forcetop2ConnectionString {
            get {
                return ((string)(this["b2b_forcetop2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-variant2;Integrated Security=True")]
        public string b2b_variant2ConnectionString {
            get {
                return ((string)(this["b2b_variant2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-bioplanet;Integrated Security=True" +
            "")]
        public string b2b_bioplanetConnectionString {
            get {
                return ((string)(this["b2b_bioplanetConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=b2b-sanero;Integrated Security=True")]
        public string b2b_saneroConnectionString {
            get {
                return ((string)(this["b2b_saneroConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex;Initial Catalog=b2b-solex;Integrated Security=True")]
        public string b2b_solexConnectionString {
            get {
                return ((string)(this["b2b_solexConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=b2b-rombor;Integrated Security=True")]
        public string b2b_romborConnectionString {
            get {
                return ((string)(this["b2b_romborConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Solex;Initial Catalog=b2b-solex;Integrated Security=True")]
        public string b2b_solexConnectionString1 {
            get {
                return ((string)(this["b2b_solexConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=b2b-megima;Integrated Security=True")]
        public string b2b_megimaConnectionString4 {
            get {
                return ((string)(this["b2b_megimaConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=20.solexb2b.pl;Initial Catalog=b2b-solex;Integrated Security=True")]
        public string b2b_solexConnectionString2 {
            get {
                return ((string)(this["b2b_solexConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.99.104;Initial Catalog=b2b-solex;Integrated Security=True")]
        public string b2b_solexConnectionString3 {
            get {
                return ((string)(this["b2b_solexConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=b2b-solex-branchMateusz;Integrated Security=T" +
            "rue")]
        public string b2b_solex_branchMateuszConnectionString {
            get {
                return ((string)(this["b2b_solex_branchMateuszConnectionString"]));
            }
        }
    }
}
