<?xml version="1.0" encoding="utf-8"?><Database Name="b2b-tenzo3" Class="MainDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=solex;Initial Catalog=b2b-tenzo3;Integrated Security=True" SettingsObjectName="SolEx.Hurt.DAL.Properties.Settings" SettingsPropertyName="b2b_tenzo3ConnectionString1" Provider="System.Data.SqlClient" />
</Database>