<?xml version="1.0" encoding="utf-8"?><Database Name="CDN_KNF_Konfiguracja" Class="KonfiguracjaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=CDN_KNF_Konfiguracja;Integrated Security=True" SettingsObjectName="SolEx.Hurt.Sync.ProviderOptima.Properties.Settings" SettingsPropertyName="CDN_KNF_KonfiguracjaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="CDN.Operatorzy" Member="Operatorzies">
    <Type Name="Operatorzy">
      <Column Name="Ope_OpeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ope_BlokadaVatDoVat7" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_AkceptacjaDelegacji" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_UdostepnianieWydrukWPodgladzie" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_OdblokowanieZlecen" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_DostepDoZadanInnychOpe" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BlokadaDanychPlacowych" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BlokadaDanychPlacowychStawka" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ZmianaPoprzedniegoCzasu" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BlokadaAnulWyplaty" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BlokadaAnulNieobecIZestCzas" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_UdostepnianieAnalWPodgladzie" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_Kod" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_Nazwisko" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_Haslo" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_HasloChk" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_NTSid" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_NTKonto" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_NTLogin" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_Administrator" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_Startowa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ope_BuforNazwa" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_KsiegaGlowna" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BuforVATSpr" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BuforVATZak" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BuforKasa" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BuforOkres" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BuforAmortyz" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BuforPlace" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BuforEwid" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ZakazCenyZak" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ZmianyOffLine" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_TylkoStartowa" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_KlasycznaKlawiatura" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_Powiadamianie" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_NumerSMS" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_Email" Type="System.String" DbType="NVarChar(254) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_Telefon" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_NazwaKomputera" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_InfoPoUruchomieniu" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_InfoRazDziennie" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ZmianaLimituKred" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_PlatnosciSprzedazTrwaly" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ZmianaAtrNaZatwDok" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_PlatnosciSprzedazBufor" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ZmianaKategorii" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_Kierownik" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BlokadaZmianTowaru" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BlokadaZmianMagazynu" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BlokadaZmianMagazynuListy" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BlokadaZmianCenFA" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BlokadaZmianCenFPF" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BlokadaZmianCenPA" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BlokadaZmianCenRO" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BlokadaZmianCenZD" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BlokadaZmianCenFZ" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BlokadaFAPAdoBufora" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BlokadaPonownejFiskFAPA" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ZapisFAPApoWydruku" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ZamkniecieDnia" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_AktualizacjaKntHaMag" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ZmianaOpisuHaMag" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_MinMarzaHaMag" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BlokadaAnulowaniaHaMag" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_RozliczanieZListyHaMag" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_SymbolDlaNumeracji" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_Magazyn" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_HasloPM" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_Kasa" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_Bank" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_Parametr" Type="System.String" DbType="NVarChar(254) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_Nieaktywny" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_KodDlaDF" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_KonfigProgressLoga" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_RaportProgressLoga" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BlokadaPlac" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_BlokadaTylkoWynagrodzen" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ZmianaProcesuDomyslnego" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ModyfikacjaProcesow" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_DostepDoSkrzynkiInnychOperatorow" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_DostepDoKontInnychOperatorow" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_PrawoOdblokowaniaKontaktu" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_KopiaBezpieczenstwa" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Ope_PrawoDoZamianEFaktury" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_KotrolaCzesciPobranych" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_DetalFunkcjaPrac" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ope_UproszczoneFakturowanie" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_PrawoDoPobrCzesciMagSerw" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_PrawoDoPobrCzesciMagLok" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_Opis" Type="System.String" DbType="NVarChar(254) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_InfoData" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ope_DataZmianyHasla" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ope_BlokadaSeryjnegoUsuwania" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_PrawoDoOdblokowaniaEDeklaracji" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_DataRSS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ope_PrawoUsuwaniaMaili" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_WyswietlajWersje" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_WyswietlajInformacje" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_WyswietlajOferteComarch" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_GIDTyp" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Ope_GIDFirma" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ope_GIDNumer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ope_GIDLp" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Ope_PelneMenu" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ModulKP" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ModulKH" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ModulST" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ModulFA" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ModulMAG" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ModulPK" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ModulPKXL" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ModulANL" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ModulCRM" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ModulCRMP" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ModulKHP" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ModulDET" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ModulBIU" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ModulSRW" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ModulOBD" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ModulKB" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ModulKBP" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_ModulHAP" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_IBard24Login" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Ope_IBard24Haslo" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="Ope_IBard24Wyloguj" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_UzywaAnalizBI" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_AnalizyBI_Administrator" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_AnalizyBI_Subskrypcje" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_AnalizyBI_DodawaniePol" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_AnalizyBI_Drukowanie" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_AnalizyBI_Eksport" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_AnalizyBI_ModyfikacjaZapytania" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_AnalizyBI_ImportRaportu" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Ope_AnalizyBI_KontoGMail" Type="System.String" DbType="VarChar(254) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>