#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolEx.Hurt.Sync.ProviderOptima
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CDN_KNF_Konfiguracja")]
	public partial class KonfiguracjaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertOperatorzy(Operatorzy instance);
    partial void UpdateOperatorzy(Operatorzy instance);
    partial void DeleteOperatorzy(Operatorzy instance);
    #endregion
		
		public KonfiguracjaDataContext() : 
				base(global::SolEx.Hurt.Sync.ProviderOptima.Properties.Settings.Default.CDN_KNF_KonfiguracjaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KonfiguracjaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KonfiguracjaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KonfiguracjaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KonfiguracjaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Operatorzy> Operatorzies
		{
			get
			{
				return this.GetTable<Operatorzy>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="CDN.Operatorzy")]
	public partial class Operatorzy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ope_OpeID;
		
		private byte _Ope_BlokadaVatDoVat7;
		
		private byte _Ope_AkceptacjaDelegacji;
		
		private byte _Ope_UdostepnianieWydrukWPodgladzie;
		
		private byte _Ope_OdblokowanieZlecen;
		
		private byte _Ope_DostepDoZadanInnychOpe;
		
		private byte _Ope_BlokadaDanychPlacowych;
		
		private byte _Ope_BlokadaDanychPlacowychStawka;
		
		private byte _Ope_ZmianaPoprzedniegoCzasu;
		
		private byte _Ope_BlokadaAnulWyplaty;
		
		private byte _Ope_BlokadaAnulNieobecIZestCzas;
		
		private byte _Ope_UdostepnianieAnalWPodgladzie;
		
		private string _Ope_Kod;
		
		private string _Ope_Nazwisko;
		
		private string _Ope_Haslo;
		
		private string _Ope_HasloChk;
		
		private string _Ope_NTSid;
		
		private string _Ope_NTKonto;
		
		private byte _Ope_NTLogin;
		
		private byte _Ope_Administrator;
		
		private System.Nullable<int> _Ope_Startowa;
		
		private string _Ope_BuforNazwa;
		
		private byte _Ope_KsiegaGlowna;
		
		private byte _Ope_BuforVATSpr;
		
		private byte _Ope_BuforVATZak;
		
		private byte _Ope_BuforKasa;
		
		private byte _Ope_BuforOkres;
		
		private byte _Ope_BuforAmortyz;
		
		private byte _Ope_BuforPlace;
		
		private byte _Ope_BuforEwid;
		
		private byte _Ope_ZakazCenyZak;
		
		private byte _Ope_ZmianyOffLine;
		
		private byte _Ope_TylkoStartowa;
		
		private byte _Ope_KlasycznaKlawiatura;
		
		private byte _Ope_Powiadamianie;
		
		private string _Ope_NumerSMS;
		
		private string _Ope_Email;
		
		private string _Ope_Telefon;
		
		private string _Ope_NazwaKomputera;
		
		private byte _Ope_InfoPoUruchomieniu;
		
		private byte _Ope_InfoRazDziennie;
		
		private byte _Ope_ZmianaLimituKred;
		
		private byte _Ope_PlatnosciSprzedazTrwaly;
		
		private byte _Ope_ZmianaAtrNaZatwDok;
		
		private byte _Ope_PlatnosciSprzedazBufor;
		
		private byte _Ope_ZmianaKategorii;
		
		private byte _Ope_Kierownik;
		
		private byte _Ope_BlokadaZmianTowaru;
		
		private byte _Ope_BlokadaZmianMagazynu;
		
		private byte _Ope_BlokadaZmianMagazynuListy;
		
		private byte _Ope_BlokadaZmianCenFA;
		
		private byte _Ope_BlokadaZmianCenFPF;
		
		private byte _Ope_BlokadaZmianCenPA;
		
		private byte _Ope_BlokadaZmianCenRO;
		
		private byte _Ope_BlokadaZmianCenZD;
		
		private byte _Ope_BlokadaZmianCenFZ;
		
		private byte _Ope_BlokadaFAPAdoBufora;
		
		private byte _Ope_BlokadaPonownejFiskFAPA;
		
		private byte _Ope_ZapisFAPApoWydruku;
		
		private byte _Ope_ZamkniecieDnia;
		
		private byte _Ope_AktualizacjaKntHaMag;
		
		private byte _Ope_ZmianaOpisuHaMag;
		
		private byte _Ope_MinMarzaHaMag;
		
		private byte _Ope_BlokadaAnulowaniaHaMag;
		
		private byte _Ope_RozliczanieZListyHaMag;
		
		private string _Ope_SymbolDlaNumeracji;
		
		private string _Ope_Magazyn;
		
		private string _Ope_HasloPM;
		
		private string _Ope_Kasa;
		
		private string _Ope_Bank;
		
		private string _Ope_Parametr;
		
		private short _Ope_Nieaktywny;
		
		private string _Ope_KodDlaDF;
		
		private byte _Ope_KonfigProgressLoga;
		
		private byte _Ope_RaportProgressLoga;
		
		private byte _Ope_BlokadaPlac;
		
		private byte _Ope_BlokadaTylkoWynagrodzen;
		
		private short _Ope_ZmianaProcesuDomyslnego;
		
		private short _Ope_ModyfikacjaProcesow;
		
		private short _Ope_DostepDoSkrzynkiInnychOperatorow;
		
		private byte _Ope_DostepDoKontInnychOperatorow;
		
		private short _Ope_PrawoOdblokowaniaKontaktu;
		
		private System.Nullable<byte> _Ope_KopiaBezpieczenstwa;
		
		private short _Ope_PrawoDoZamianEFaktury;
		
		private byte _Ope_KotrolaCzesciPobranych;
		
		private int _Ope_DetalFunkcjaPrac;
		
		private byte _Ope_UproszczoneFakturowanie;
		
		private byte _Ope_PrawoDoPobrCzesciMagSerw;
		
		private byte _Ope_PrawoDoPobrCzesciMagLok;
		
		private string _Ope_Opis;
		
		private System.Nullable<System.DateTime> _Ope_InfoData;
		
		private System.Nullable<System.DateTime> _Ope_DataZmianyHasla;
		
		private byte _Ope_BlokadaSeryjnegoUsuwania;
		
		private byte _Ope_PrawoDoOdblokowaniaEDeklaracji;
		
		private System.Nullable<System.DateTime> _Ope_DataRSS;
		
		private byte _Ope_PrawoUsuwaniaMaili;
		
		private byte _Ope_WyswietlajWersje;
		
		private byte _Ope_WyswietlajInformacje;
		
		private byte _Ope_WyswietlajOferteComarch;
		
		private System.Nullable<short> _Ope_GIDTyp;
		
		private System.Nullable<int> _Ope_GIDFirma;
		
		private System.Nullable<int> _Ope_GIDNumer;
		
		private System.Nullable<short> _Ope_GIDLp;
		
		private byte _Ope_PelneMenu;
		
		private byte _Ope_ModulKP;
		
		private byte _Ope_ModulKH;
		
		private byte _Ope_ModulST;
		
		private byte _Ope_ModulFA;
		
		private byte _Ope_ModulMAG;
		
		private byte _Ope_ModulPK;
		
		private byte _Ope_ModulPKXL;
		
		private byte _Ope_ModulANL;
		
		private byte _Ope_ModulCRM;
		
		private byte _Ope_ModulCRMP;
		
		private byte _Ope_ModulKHP;
		
		private byte _Ope_ModulDET;
		
		private byte _Ope_ModulBIU;
		
		private byte _Ope_ModulSRW;
		
		private byte _Ope_ModulOBD;
		
		private byte _Ope_ModulKB;
		
		private byte _Ope_ModulKBP;
		
		private byte _Ope_ModulHAP;
		
		private string _Ope_IBard24Login;
		
		private string _Ope_IBard24Haslo;
		
		private byte _Ope_IBard24Wyloguj;
		
		private byte _Ope_UzywaAnalizBI;
		
		private byte _Ope_AnalizyBI_Administrator;
		
		private byte _Ope_AnalizyBI_Subskrypcje;
		
		private byte _Ope_AnalizyBI_DodawaniePol;
		
		private byte _Ope_AnalizyBI_Drukowanie;
		
		private byte _Ope_AnalizyBI_Eksport;
		
		private byte _Ope_AnalizyBI_ModyfikacjaZapytania;
		
		private byte _Ope_AnalizyBI_ImportRaportu;
		
		private string _Ope_AnalizyBI_KontoGMail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOpe_OpeIDChanging(int value);
    partial void OnOpe_OpeIDChanged();
    partial void OnOpe_BlokadaVatDoVat7Changing(byte value);
    partial void OnOpe_BlokadaVatDoVat7Changed();
    partial void OnOpe_AkceptacjaDelegacjiChanging(byte value);
    partial void OnOpe_AkceptacjaDelegacjiChanged();
    partial void OnOpe_UdostepnianieWydrukWPodgladzieChanging(byte value);
    partial void OnOpe_UdostepnianieWydrukWPodgladzieChanged();
    partial void OnOpe_OdblokowanieZlecenChanging(byte value);
    partial void OnOpe_OdblokowanieZlecenChanged();
    partial void OnOpe_DostepDoZadanInnychOpeChanging(byte value);
    partial void OnOpe_DostepDoZadanInnychOpeChanged();
    partial void OnOpe_BlokadaDanychPlacowychChanging(byte value);
    partial void OnOpe_BlokadaDanychPlacowychChanged();
    partial void OnOpe_BlokadaDanychPlacowychStawkaChanging(byte value);
    partial void OnOpe_BlokadaDanychPlacowychStawkaChanged();
    partial void OnOpe_ZmianaPoprzedniegoCzasuChanging(byte value);
    partial void OnOpe_ZmianaPoprzedniegoCzasuChanged();
    partial void OnOpe_BlokadaAnulWyplatyChanging(byte value);
    partial void OnOpe_BlokadaAnulWyplatyChanged();
    partial void OnOpe_BlokadaAnulNieobecIZestCzasChanging(byte value);
    partial void OnOpe_BlokadaAnulNieobecIZestCzasChanged();
    partial void OnOpe_UdostepnianieAnalWPodgladzieChanging(byte value);
    partial void OnOpe_UdostepnianieAnalWPodgladzieChanged();
    partial void OnOpe_KodChanging(string value);
    partial void OnOpe_KodChanged();
    partial void OnOpe_NazwiskoChanging(string value);
    partial void OnOpe_NazwiskoChanged();
    partial void OnOpe_HasloChanging(string value);
    partial void OnOpe_HasloChanged();
    partial void OnOpe_HasloChkChanging(string value);
    partial void OnOpe_HasloChkChanged();
    partial void OnOpe_NTSidChanging(string value);
    partial void OnOpe_NTSidChanged();
    partial void OnOpe_NTKontoChanging(string value);
    partial void OnOpe_NTKontoChanged();
    partial void OnOpe_NTLoginChanging(byte value);
    partial void OnOpe_NTLoginChanged();
    partial void OnOpe_AdministratorChanging(byte value);
    partial void OnOpe_AdministratorChanged();
    partial void OnOpe_StartowaChanging(System.Nullable<int> value);
    partial void OnOpe_StartowaChanged();
    partial void OnOpe_BuforNazwaChanging(string value);
    partial void OnOpe_BuforNazwaChanged();
    partial void OnOpe_KsiegaGlownaChanging(byte value);
    partial void OnOpe_KsiegaGlownaChanged();
    partial void OnOpe_BuforVATSprChanging(byte value);
    partial void OnOpe_BuforVATSprChanged();
    partial void OnOpe_BuforVATZakChanging(byte value);
    partial void OnOpe_BuforVATZakChanged();
    partial void OnOpe_BuforKasaChanging(byte value);
    partial void OnOpe_BuforKasaChanged();
    partial void OnOpe_BuforOkresChanging(byte value);
    partial void OnOpe_BuforOkresChanged();
    partial void OnOpe_BuforAmortyzChanging(byte value);
    partial void OnOpe_BuforAmortyzChanged();
    partial void OnOpe_BuforPlaceChanging(byte value);
    partial void OnOpe_BuforPlaceChanged();
    partial void OnOpe_BuforEwidChanging(byte value);
    partial void OnOpe_BuforEwidChanged();
    partial void OnOpe_ZakazCenyZakChanging(byte value);
    partial void OnOpe_ZakazCenyZakChanged();
    partial void OnOpe_ZmianyOffLineChanging(byte value);
    partial void OnOpe_ZmianyOffLineChanged();
    partial void OnOpe_TylkoStartowaChanging(byte value);
    partial void OnOpe_TylkoStartowaChanged();
    partial void OnOpe_KlasycznaKlawiaturaChanging(byte value);
    partial void OnOpe_KlasycznaKlawiaturaChanged();
    partial void OnOpe_PowiadamianieChanging(byte value);
    partial void OnOpe_PowiadamianieChanged();
    partial void OnOpe_NumerSMSChanging(string value);
    partial void OnOpe_NumerSMSChanged();
    partial void OnOpe_EmailChanging(string value);
    partial void OnOpe_EmailChanged();
    partial void OnOpe_TelefonChanging(string value);
    partial void OnOpe_TelefonChanged();
    partial void OnOpe_NazwaKomputeraChanging(string value);
    partial void OnOpe_NazwaKomputeraChanged();
    partial void OnOpe_InfoPoUruchomieniuChanging(byte value);
    partial void OnOpe_InfoPoUruchomieniuChanged();
    partial void OnOpe_InfoRazDziennieChanging(byte value);
    partial void OnOpe_InfoRazDziennieChanged();
    partial void OnOpe_ZmianaLimituKredChanging(byte value);
    partial void OnOpe_ZmianaLimituKredChanged();
    partial void OnOpe_PlatnosciSprzedazTrwalyChanging(byte value);
    partial void OnOpe_PlatnosciSprzedazTrwalyChanged();
    partial void OnOpe_ZmianaAtrNaZatwDokChanging(byte value);
    partial void OnOpe_ZmianaAtrNaZatwDokChanged();
    partial void OnOpe_PlatnosciSprzedazBuforChanging(byte value);
    partial void OnOpe_PlatnosciSprzedazBuforChanged();
    partial void OnOpe_ZmianaKategoriiChanging(byte value);
    partial void OnOpe_ZmianaKategoriiChanged();
    partial void OnOpe_KierownikChanging(byte value);
    partial void OnOpe_KierownikChanged();
    partial void OnOpe_BlokadaZmianTowaruChanging(byte value);
    partial void OnOpe_BlokadaZmianTowaruChanged();
    partial void OnOpe_BlokadaZmianMagazynuChanging(byte value);
    partial void OnOpe_BlokadaZmianMagazynuChanged();
    partial void OnOpe_BlokadaZmianMagazynuListyChanging(byte value);
    partial void OnOpe_BlokadaZmianMagazynuListyChanged();
    partial void OnOpe_BlokadaZmianCenFAChanging(byte value);
    partial void OnOpe_BlokadaZmianCenFAChanged();
    partial void OnOpe_BlokadaZmianCenFPFChanging(byte value);
    partial void OnOpe_BlokadaZmianCenFPFChanged();
    partial void OnOpe_BlokadaZmianCenPAChanging(byte value);
    partial void OnOpe_BlokadaZmianCenPAChanged();
    partial void OnOpe_BlokadaZmianCenROChanging(byte value);
    partial void OnOpe_BlokadaZmianCenROChanged();
    partial void OnOpe_BlokadaZmianCenZDChanging(byte value);
    partial void OnOpe_BlokadaZmianCenZDChanged();
    partial void OnOpe_BlokadaZmianCenFZChanging(byte value);
    partial void OnOpe_BlokadaZmianCenFZChanged();
    partial void OnOpe_BlokadaFAPAdoBuforaChanging(byte value);
    partial void OnOpe_BlokadaFAPAdoBuforaChanged();
    partial void OnOpe_BlokadaPonownejFiskFAPAChanging(byte value);
    partial void OnOpe_BlokadaPonownejFiskFAPAChanged();
    partial void OnOpe_ZapisFAPApoWydrukuChanging(byte value);
    partial void OnOpe_ZapisFAPApoWydrukuChanged();
    partial void OnOpe_ZamkniecieDniaChanging(byte value);
    partial void OnOpe_ZamkniecieDniaChanged();
    partial void OnOpe_AktualizacjaKntHaMagChanging(byte value);
    partial void OnOpe_AktualizacjaKntHaMagChanged();
    partial void OnOpe_ZmianaOpisuHaMagChanging(byte value);
    partial void OnOpe_ZmianaOpisuHaMagChanged();
    partial void OnOpe_MinMarzaHaMagChanging(byte value);
    partial void OnOpe_MinMarzaHaMagChanged();
    partial void OnOpe_BlokadaAnulowaniaHaMagChanging(byte value);
    partial void OnOpe_BlokadaAnulowaniaHaMagChanged();
    partial void OnOpe_RozliczanieZListyHaMagChanging(byte value);
    partial void OnOpe_RozliczanieZListyHaMagChanged();
    partial void OnOpe_SymbolDlaNumeracjiChanging(string value);
    partial void OnOpe_SymbolDlaNumeracjiChanged();
    partial void OnOpe_MagazynChanging(string value);
    partial void OnOpe_MagazynChanged();
    partial void OnOpe_HasloPMChanging(string value);
    partial void OnOpe_HasloPMChanged();
    partial void OnOpe_KasaChanging(string value);
    partial void OnOpe_KasaChanged();
    partial void OnOpe_BankChanging(string value);
    partial void OnOpe_BankChanged();
    partial void OnOpe_ParametrChanging(string value);
    partial void OnOpe_ParametrChanged();
    partial void OnOpe_NieaktywnyChanging(short value);
    partial void OnOpe_NieaktywnyChanged();
    partial void OnOpe_KodDlaDFChanging(string value);
    partial void OnOpe_KodDlaDFChanged();
    partial void OnOpe_KonfigProgressLogaChanging(byte value);
    partial void OnOpe_KonfigProgressLogaChanged();
    partial void OnOpe_RaportProgressLogaChanging(byte value);
    partial void OnOpe_RaportProgressLogaChanged();
    partial void OnOpe_BlokadaPlacChanging(byte value);
    partial void OnOpe_BlokadaPlacChanged();
    partial void OnOpe_BlokadaTylkoWynagrodzenChanging(byte value);
    partial void OnOpe_BlokadaTylkoWynagrodzenChanged();
    partial void OnOpe_ZmianaProcesuDomyslnegoChanging(short value);
    partial void OnOpe_ZmianaProcesuDomyslnegoChanged();
    partial void OnOpe_ModyfikacjaProcesowChanging(short value);
    partial void OnOpe_ModyfikacjaProcesowChanged();
    partial void OnOpe_DostepDoSkrzynkiInnychOperatorowChanging(short value);
    partial void OnOpe_DostepDoSkrzynkiInnychOperatorowChanged();
    partial void OnOpe_DostepDoKontInnychOperatorowChanging(byte value);
    partial void OnOpe_DostepDoKontInnychOperatorowChanged();
    partial void OnOpe_PrawoOdblokowaniaKontaktuChanging(short value);
    partial void OnOpe_PrawoOdblokowaniaKontaktuChanged();
    partial void OnOpe_KopiaBezpieczenstwaChanging(System.Nullable<byte> value);
    partial void OnOpe_KopiaBezpieczenstwaChanged();
    partial void OnOpe_PrawoDoZamianEFakturyChanging(short value);
    partial void OnOpe_PrawoDoZamianEFakturyChanged();
    partial void OnOpe_KotrolaCzesciPobranychChanging(byte value);
    partial void OnOpe_KotrolaCzesciPobranychChanged();
    partial void OnOpe_DetalFunkcjaPracChanging(int value);
    partial void OnOpe_DetalFunkcjaPracChanged();
    partial void OnOpe_UproszczoneFakturowanieChanging(byte value);
    partial void OnOpe_UproszczoneFakturowanieChanged();
    partial void OnOpe_PrawoDoPobrCzesciMagSerwChanging(byte value);
    partial void OnOpe_PrawoDoPobrCzesciMagSerwChanged();
    partial void OnOpe_PrawoDoPobrCzesciMagLokChanging(byte value);
    partial void OnOpe_PrawoDoPobrCzesciMagLokChanged();
    partial void OnOpe_OpisChanging(string value);
    partial void OnOpe_OpisChanged();
    partial void OnOpe_InfoDataChanging(System.Nullable<System.DateTime> value);
    partial void OnOpe_InfoDataChanged();
    partial void OnOpe_DataZmianyHaslaChanging(System.Nullable<System.DateTime> value);
    partial void OnOpe_DataZmianyHaslaChanged();
    partial void OnOpe_BlokadaSeryjnegoUsuwaniaChanging(byte value);
    partial void OnOpe_BlokadaSeryjnegoUsuwaniaChanged();
    partial void OnOpe_PrawoDoOdblokowaniaEDeklaracjiChanging(byte value);
    partial void OnOpe_PrawoDoOdblokowaniaEDeklaracjiChanged();
    partial void OnOpe_DataRSSChanging(System.Nullable<System.DateTime> value);
    partial void OnOpe_DataRSSChanged();
    partial void OnOpe_PrawoUsuwaniaMailiChanging(byte value);
    partial void OnOpe_PrawoUsuwaniaMailiChanged();
    partial void OnOpe_WyswietlajWersjeChanging(byte value);
    partial void OnOpe_WyswietlajWersjeChanged();
    partial void OnOpe_WyswietlajInformacjeChanging(byte value);
    partial void OnOpe_WyswietlajInformacjeChanged();
    partial void OnOpe_WyswietlajOferteComarchChanging(byte value);
    partial void OnOpe_WyswietlajOferteComarchChanged();
    partial void OnOpe_GIDTypChanging(System.Nullable<short> value);
    partial void OnOpe_GIDTypChanged();
    partial void OnOpe_GIDFirmaChanging(System.Nullable<int> value);
    partial void OnOpe_GIDFirmaChanged();
    partial void OnOpe_GIDNumerChanging(System.Nullable<int> value);
    partial void OnOpe_GIDNumerChanged();
    partial void OnOpe_GIDLpChanging(System.Nullable<short> value);
    partial void OnOpe_GIDLpChanged();
    partial void OnOpe_PelneMenuChanging(byte value);
    partial void OnOpe_PelneMenuChanged();
    partial void OnOpe_ModulKPChanging(byte value);
    partial void OnOpe_ModulKPChanged();
    partial void OnOpe_ModulKHChanging(byte value);
    partial void OnOpe_ModulKHChanged();
    partial void OnOpe_ModulSTChanging(byte value);
    partial void OnOpe_ModulSTChanged();
    partial void OnOpe_ModulFAChanging(byte value);
    partial void OnOpe_ModulFAChanged();
    partial void OnOpe_ModulMAGChanging(byte value);
    partial void OnOpe_ModulMAGChanged();
    partial void OnOpe_ModulPKChanging(byte value);
    partial void OnOpe_ModulPKChanged();
    partial void OnOpe_ModulPKXLChanging(byte value);
    partial void OnOpe_ModulPKXLChanged();
    partial void OnOpe_ModulANLChanging(byte value);
    partial void OnOpe_ModulANLChanged();
    partial void OnOpe_ModulCRMChanging(byte value);
    partial void OnOpe_ModulCRMChanged();
    partial void OnOpe_ModulCRMPChanging(byte value);
    partial void OnOpe_ModulCRMPChanged();
    partial void OnOpe_ModulKHPChanging(byte value);
    partial void OnOpe_ModulKHPChanged();
    partial void OnOpe_ModulDETChanging(byte value);
    partial void OnOpe_ModulDETChanged();
    partial void OnOpe_ModulBIUChanging(byte value);
    partial void OnOpe_ModulBIUChanged();
    partial void OnOpe_ModulSRWChanging(byte value);
    partial void OnOpe_ModulSRWChanged();
    partial void OnOpe_ModulOBDChanging(byte value);
    partial void OnOpe_ModulOBDChanged();
    partial void OnOpe_ModulKBChanging(byte value);
    partial void OnOpe_ModulKBChanged();
    partial void OnOpe_ModulKBPChanging(byte value);
    partial void OnOpe_ModulKBPChanged();
    partial void OnOpe_ModulHAPChanging(byte value);
    partial void OnOpe_ModulHAPChanged();
    partial void OnOpe_IBard24LoginChanging(string value);
    partial void OnOpe_IBard24LoginChanged();
    partial void OnOpe_IBard24HasloChanging(string value);
    partial void OnOpe_IBard24HasloChanged();
    partial void OnOpe_IBard24WylogujChanging(byte value);
    partial void OnOpe_IBard24WylogujChanged();
    partial void OnOpe_UzywaAnalizBIChanging(byte value);
    partial void OnOpe_UzywaAnalizBIChanged();
    partial void OnOpe_AnalizyBI_AdministratorChanging(byte value);
    partial void OnOpe_AnalizyBI_AdministratorChanged();
    partial void OnOpe_AnalizyBI_SubskrypcjeChanging(byte value);
    partial void OnOpe_AnalizyBI_SubskrypcjeChanged();
    partial void OnOpe_AnalizyBI_DodawaniePolChanging(byte value);
    partial void OnOpe_AnalizyBI_DodawaniePolChanged();
    partial void OnOpe_AnalizyBI_DrukowanieChanging(byte value);
    partial void OnOpe_AnalizyBI_DrukowanieChanged();
    partial void OnOpe_AnalizyBI_EksportChanging(byte value);
    partial void OnOpe_AnalizyBI_EksportChanged();
    partial void OnOpe_AnalizyBI_ModyfikacjaZapytaniaChanging(byte value);
    partial void OnOpe_AnalizyBI_ModyfikacjaZapytaniaChanged();
    partial void OnOpe_AnalizyBI_ImportRaportuChanging(byte value);
    partial void OnOpe_AnalizyBI_ImportRaportuChanged();
    partial void OnOpe_AnalizyBI_KontoGMailChanging(string value);
    partial void OnOpe_AnalizyBI_KontoGMailChanged();
    #endregion
		
		public Operatorzy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_OpeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ope_OpeID
		{
			get
			{
				return this._Ope_OpeID;
			}
			set
			{
				if ((this._Ope_OpeID != value))
				{
					this.OnOpe_OpeIDChanging(value);
					this.SendPropertyChanging();
					this._Ope_OpeID = value;
					this.SendPropertyChanged("Ope_OpeID");
					this.OnOpe_OpeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaVatDoVat7", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaVatDoVat7
		{
			get
			{
				return this._Ope_BlokadaVatDoVat7;
			}
			set
			{
				if ((this._Ope_BlokadaVatDoVat7 != value))
				{
					this.OnOpe_BlokadaVatDoVat7Changing(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaVatDoVat7 = value;
					this.SendPropertyChanged("Ope_BlokadaVatDoVat7");
					this.OnOpe_BlokadaVatDoVat7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_AkceptacjaDelegacji", DbType="TinyInt NOT NULL")]
		public byte Ope_AkceptacjaDelegacji
		{
			get
			{
				return this._Ope_AkceptacjaDelegacji;
			}
			set
			{
				if ((this._Ope_AkceptacjaDelegacji != value))
				{
					this.OnOpe_AkceptacjaDelegacjiChanging(value);
					this.SendPropertyChanging();
					this._Ope_AkceptacjaDelegacji = value;
					this.SendPropertyChanged("Ope_AkceptacjaDelegacji");
					this.OnOpe_AkceptacjaDelegacjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_UdostepnianieWydrukWPodgladzie", DbType="TinyInt NOT NULL")]
		public byte Ope_UdostepnianieWydrukWPodgladzie
		{
			get
			{
				return this._Ope_UdostepnianieWydrukWPodgladzie;
			}
			set
			{
				if ((this._Ope_UdostepnianieWydrukWPodgladzie != value))
				{
					this.OnOpe_UdostepnianieWydrukWPodgladzieChanging(value);
					this.SendPropertyChanging();
					this._Ope_UdostepnianieWydrukWPodgladzie = value;
					this.SendPropertyChanged("Ope_UdostepnianieWydrukWPodgladzie");
					this.OnOpe_UdostepnianieWydrukWPodgladzieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_OdblokowanieZlecen", DbType="TinyInt NOT NULL")]
		public byte Ope_OdblokowanieZlecen
		{
			get
			{
				return this._Ope_OdblokowanieZlecen;
			}
			set
			{
				if ((this._Ope_OdblokowanieZlecen != value))
				{
					this.OnOpe_OdblokowanieZlecenChanging(value);
					this.SendPropertyChanging();
					this._Ope_OdblokowanieZlecen = value;
					this.SendPropertyChanged("Ope_OdblokowanieZlecen");
					this.OnOpe_OdblokowanieZlecenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_DostepDoZadanInnychOpe", DbType="TinyInt NOT NULL")]
		public byte Ope_DostepDoZadanInnychOpe
		{
			get
			{
				return this._Ope_DostepDoZadanInnychOpe;
			}
			set
			{
				if ((this._Ope_DostepDoZadanInnychOpe != value))
				{
					this.OnOpe_DostepDoZadanInnychOpeChanging(value);
					this.SendPropertyChanging();
					this._Ope_DostepDoZadanInnychOpe = value;
					this.SendPropertyChanged("Ope_DostepDoZadanInnychOpe");
					this.OnOpe_DostepDoZadanInnychOpeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaDanychPlacowych", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaDanychPlacowych
		{
			get
			{
				return this._Ope_BlokadaDanychPlacowych;
			}
			set
			{
				if ((this._Ope_BlokadaDanychPlacowych != value))
				{
					this.OnOpe_BlokadaDanychPlacowychChanging(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaDanychPlacowych = value;
					this.SendPropertyChanged("Ope_BlokadaDanychPlacowych");
					this.OnOpe_BlokadaDanychPlacowychChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaDanychPlacowychStawka", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaDanychPlacowychStawka
		{
			get
			{
				return this._Ope_BlokadaDanychPlacowychStawka;
			}
			set
			{
				if ((this._Ope_BlokadaDanychPlacowychStawka != value))
				{
					this.OnOpe_BlokadaDanychPlacowychStawkaChanging(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaDanychPlacowychStawka = value;
					this.SendPropertyChanged("Ope_BlokadaDanychPlacowychStawka");
					this.OnOpe_BlokadaDanychPlacowychStawkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ZmianaPoprzedniegoCzasu", DbType="TinyInt NOT NULL")]
		public byte Ope_ZmianaPoprzedniegoCzasu
		{
			get
			{
				return this._Ope_ZmianaPoprzedniegoCzasu;
			}
			set
			{
				if ((this._Ope_ZmianaPoprzedniegoCzasu != value))
				{
					this.OnOpe_ZmianaPoprzedniegoCzasuChanging(value);
					this.SendPropertyChanging();
					this._Ope_ZmianaPoprzedniegoCzasu = value;
					this.SendPropertyChanged("Ope_ZmianaPoprzedniegoCzasu");
					this.OnOpe_ZmianaPoprzedniegoCzasuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaAnulWyplaty", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaAnulWyplaty
		{
			get
			{
				return this._Ope_BlokadaAnulWyplaty;
			}
			set
			{
				if ((this._Ope_BlokadaAnulWyplaty != value))
				{
					this.OnOpe_BlokadaAnulWyplatyChanging(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaAnulWyplaty = value;
					this.SendPropertyChanged("Ope_BlokadaAnulWyplaty");
					this.OnOpe_BlokadaAnulWyplatyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaAnulNieobecIZestCzas", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaAnulNieobecIZestCzas
		{
			get
			{
				return this._Ope_BlokadaAnulNieobecIZestCzas;
			}
			set
			{
				if ((this._Ope_BlokadaAnulNieobecIZestCzas != value))
				{
					this.OnOpe_BlokadaAnulNieobecIZestCzasChanging(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaAnulNieobecIZestCzas = value;
					this.SendPropertyChanged("Ope_BlokadaAnulNieobecIZestCzas");
					this.OnOpe_BlokadaAnulNieobecIZestCzasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_UdostepnianieAnalWPodgladzie", DbType="TinyInt NOT NULL")]
		public byte Ope_UdostepnianieAnalWPodgladzie
		{
			get
			{
				return this._Ope_UdostepnianieAnalWPodgladzie;
			}
			set
			{
				if ((this._Ope_UdostepnianieAnalWPodgladzie != value))
				{
					this.OnOpe_UdostepnianieAnalWPodgladzieChanging(value);
					this.SendPropertyChanging();
					this._Ope_UdostepnianieAnalWPodgladzie = value;
					this.SendPropertyChanged("Ope_UdostepnianieAnalWPodgladzie");
					this.OnOpe_UdostepnianieAnalWPodgladzieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_Kod", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Ope_Kod
		{
			get
			{
				return this._Ope_Kod;
			}
			set
			{
				if ((this._Ope_Kod != value))
				{
					this.OnOpe_KodChanging(value);
					this.SendPropertyChanging();
					this._Ope_Kod = value;
					this.SendPropertyChanged("Ope_Kod");
					this.OnOpe_KodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_Nazwisko", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ope_Nazwisko
		{
			get
			{
				return this._Ope_Nazwisko;
			}
			set
			{
				if ((this._Ope_Nazwisko != value))
				{
					this.OnOpe_NazwiskoChanging(value);
					this.SendPropertyChanging();
					this._Ope_Nazwisko = value;
					this.SendPropertyChanged("Ope_Nazwisko");
					this.OnOpe_NazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_Haslo", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
		public string Ope_Haslo
		{
			get
			{
				return this._Ope_Haslo;
			}
			set
			{
				if ((this._Ope_Haslo != value))
				{
					this.OnOpe_HasloChanging(value);
					this.SendPropertyChanging();
					this._Ope_Haslo = value;
					this.SendPropertyChanged("Ope_Haslo");
					this.OnOpe_HasloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_HasloChk", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string Ope_HasloChk
		{
			get
			{
				return this._Ope_HasloChk;
			}
			set
			{
				if ((this._Ope_HasloChk != value))
				{
					this.OnOpe_HasloChkChanging(value);
					this.SendPropertyChanging();
					this._Ope_HasloChk = value;
					this.SendPropertyChanged("Ope_HasloChk");
					this.OnOpe_HasloChkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_NTSid", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Ope_NTSid
		{
			get
			{
				return this._Ope_NTSid;
			}
			set
			{
				if ((this._Ope_NTSid != value))
				{
					this.OnOpe_NTSidChanging(value);
					this.SendPropertyChanging();
					this._Ope_NTSid = value;
					this.SendPropertyChanged("Ope_NTSid");
					this.OnOpe_NTSidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_NTKonto", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Ope_NTKonto
		{
			get
			{
				return this._Ope_NTKonto;
			}
			set
			{
				if ((this._Ope_NTKonto != value))
				{
					this.OnOpe_NTKontoChanging(value);
					this.SendPropertyChanging();
					this._Ope_NTKonto = value;
					this.SendPropertyChanged("Ope_NTKonto");
					this.OnOpe_NTKontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_NTLogin", DbType="TinyInt NOT NULL")]
		public byte Ope_NTLogin
		{
			get
			{
				return this._Ope_NTLogin;
			}
			set
			{
				if ((this._Ope_NTLogin != value))
				{
					this.OnOpe_NTLoginChanging(value);
					this.SendPropertyChanging();
					this._Ope_NTLogin = value;
					this.SendPropertyChanged("Ope_NTLogin");
					this.OnOpe_NTLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_Administrator", DbType="TinyInt NOT NULL")]
		public byte Ope_Administrator
		{
			get
			{
				return this._Ope_Administrator;
			}
			set
			{
				if ((this._Ope_Administrator != value))
				{
					this.OnOpe_AdministratorChanging(value);
					this.SendPropertyChanging();
					this._Ope_Administrator = value;
					this.SendPropertyChanged("Ope_Administrator");
					this.OnOpe_AdministratorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_Startowa", DbType="Int")]
		public System.Nullable<int> Ope_Startowa
		{
			get
			{
				return this._Ope_Startowa;
			}
			set
			{
				if ((this._Ope_Startowa != value))
				{
					this.OnOpe_StartowaChanging(value);
					this.SendPropertyChanging();
					this._Ope_Startowa = value;
					this.SendPropertyChanged("Ope_Startowa");
					this.OnOpe_StartowaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BuforNazwa", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Ope_BuforNazwa
		{
			get
			{
				return this._Ope_BuforNazwa;
			}
			set
			{
				if ((this._Ope_BuforNazwa != value))
				{
					this.OnOpe_BuforNazwaChanging(value);
					this.SendPropertyChanging();
					this._Ope_BuforNazwa = value;
					this.SendPropertyChanged("Ope_BuforNazwa");
					this.OnOpe_BuforNazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_KsiegaGlowna", DbType="TinyInt NOT NULL")]
		public byte Ope_KsiegaGlowna
		{
			get
			{
				return this._Ope_KsiegaGlowna;
			}
			set
			{
				if ((this._Ope_KsiegaGlowna != value))
				{
					this.OnOpe_KsiegaGlownaChanging(value);
					this.SendPropertyChanging();
					this._Ope_KsiegaGlowna = value;
					this.SendPropertyChanged("Ope_KsiegaGlowna");
					this.OnOpe_KsiegaGlownaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BuforVATSpr", DbType="TinyInt NOT NULL")]
		public byte Ope_BuforVATSpr
		{
			get
			{
				return this._Ope_BuforVATSpr;
			}
			set
			{
				if ((this._Ope_BuforVATSpr != value))
				{
					this.OnOpe_BuforVATSprChanging(value);
					this.SendPropertyChanging();
					this._Ope_BuforVATSpr = value;
					this.SendPropertyChanged("Ope_BuforVATSpr");
					this.OnOpe_BuforVATSprChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BuforVATZak", DbType="TinyInt NOT NULL")]
		public byte Ope_BuforVATZak
		{
			get
			{
				return this._Ope_BuforVATZak;
			}
			set
			{
				if ((this._Ope_BuforVATZak != value))
				{
					this.OnOpe_BuforVATZakChanging(value);
					this.SendPropertyChanging();
					this._Ope_BuforVATZak = value;
					this.SendPropertyChanged("Ope_BuforVATZak");
					this.OnOpe_BuforVATZakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BuforKasa", DbType="TinyInt NOT NULL")]
		public byte Ope_BuforKasa
		{
			get
			{
				return this._Ope_BuforKasa;
			}
			set
			{
				if ((this._Ope_BuforKasa != value))
				{
					this.OnOpe_BuforKasaChanging(value);
					this.SendPropertyChanging();
					this._Ope_BuforKasa = value;
					this.SendPropertyChanged("Ope_BuforKasa");
					this.OnOpe_BuforKasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BuforOkres", DbType="TinyInt NOT NULL")]
		public byte Ope_BuforOkres
		{
			get
			{
				return this._Ope_BuforOkres;
			}
			set
			{
				if ((this._Ope_BuforOkres != value))
				{
					this.OnOpe_BuforOkresChanging(value);
					this.SendPropertyChanging();
					this._Ope_BuforOkres = value;
					this.SendPropertyChanged("Ope_BuforOkres");
					this.OnOpe_BuforOkresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BuforAmortyz", DbType="TinyInt NOT NULL")]
		public byte Ope_BuforAmortyz
		{
			get
			{
				return this._Ope_BuforAmortyz;
			}
			set
			{
				if ((this._Ope_BuforAmortyz != value))
				{
					this.OnOpe_BuforAmortyzChanging(value);
					this.SendPropertyChanging();
					this._Ope_BuforAmortyz = value;
					this.SendPropertyChanged("Ope_BuforAmortyz");
					this.OnOpe_BuforAmortyzChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BuforPlace", DbType="TinyInt NOT NULL")]
		public byte Ope_BuforPlace
		{
			get
			{
				return this._Ope_BuforPlace;
			}
			set
			{
				if ((this._Ope_BuforPlace != value))
				{
					this.OnOpe_BuforPlaceChanging(value);
					this.SendPropertyChanging();
					this._Ope_BuforPlace = value;
					this.SendPropertyChanged("Ope_BuforPlace");
					this.OnOpe_BuforPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BuforEwid", DbType="TinyInt NOT NULL")]
		public byte Ope_BuforEwid
		{
			get
			{
				return this._Ope_BuforEwid;
			}
			set
			{
				if ((this._Ope_BuforEwid != value))
				{
					this.OnOpe_BuforEwidChanging(value);
					this.SendPropertyChanging();
					this._Ope_BuforEwid = value;
					this.SendPropertyChanged("Ope_BuforEwid");
					this.OnOpe_BuforEwidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ZakazCenyZak", DbType="TinyInt NOT NULL")]
		public byte Ope_ZakazCenyZak
		{
			get
			{
				return this._Ope_ZakazCenyZak;
			}
			set
			{
				if ((this._Ope_ZakazCenyZak != value))
				{
					this.OnOpe_ZakazCenyZakChanging(value);
					this.SendPropertyChanging();
					this._Ope_ZakazCenyZak = value;
					this.SendPropertyChanged("Ope_ZakazCenyZak");
					this.OnOpe_ZakazCenyZakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ZmianyOffLine", DbType="TinyInt NOT NULL")]
		public byte Ope_ZmianyOffLine
		{
			get
			{
				return this._Ope_ZmianyOffLine;
			}
			set
			{
				if ((this._Ope_ZmianyOffLine != value))
				{
					this.OnOpe_ZmianyOffLineChanging(value);
					this.SendPropertyChanging();
					this._Ope_ZmianyOffLine = value;
					this.SendPropertyChanged("Ope_ZmianyOffLine");
					this.OnOpe_ZmianyOffLineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_TylkoStartowa", DbType="TinyInt NOT NULL")]
		public byte Ope_TylkoStartowa
		{
			get
			{
				return this._Ope_TylkoStartowa;
			}
			set
			{
				if ((this._Ope_TylkoStartowa != value))
				{
					this.OnOpe_TylkoStartowaChanging(value);
					this.SendPropertyChanging();
					this._Ope_TylkoStartowa = value;
					this.SendPropertyChanged("Ope_TylkoStartowa");
					this.OnOpe_TylkoStartowaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_KlasycznaKlawiatura", DbType="TinyInt NOT NULL")]
		public byte Ope_KlasycznaKlawiatura
		{
			get
			{
				return this._Ope_KlasycznaKlawiatura;
			}
			set
			{
				if ((this._Ope_KlasycznaKlawiatura != value))
				{
					this.OnOpe_KlasycznaKlawiaturaChanging(value);
					this.SendPropertyChanging();
					this._Ope_KlasycznaKlawiatura = value;
					this.SendPropertyChanged("Ope_KlasycznaKlawiatura");
					this.OnOpe_KlasycznaKlawiaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_Powiadamianie", DbType="TinyInt NOT NULL")]
		public byte Ope_Powiadamianie
		{
			get
			{
				return this._Ope_Powiadamianie;
			}
			set
			{
				if ((this._Ope_Powiadamianie != value))
				{
					this.OnOpe_PowiadamianieChanging(value);
					this.SendPropertyChanging();
					this._Ope_Powiadamianie = value;
					this.SendPropertyChanged("Ope_Powiadamianie");
					this.OnOpe_PowiadamianieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_NumerSMS", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Ope_NumerSMS
		{
			get
			{
				return this._Ope_NumerSMS;
			}
			set
			{
				if ((this._Ope_NumerSMS != value))
				{
					this.OnOpe_NumerSMSChanging(value);
					this.SendPropertyChanging();
					this._Ope_NumerSMS = value;
					this.SendPropertyChanged("Ope_NumerSMS");
					this.OnOpe_NumerSMSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_Email", DbType="NVarChar(254) NOT NULL", CanBeNull=false)]
		public string Ope_Email
		{
			get
			{
				return this._Ope_Email;
			}
			set
			{
				if ((this._Ope_Email != value))
				{
					this.OnOpe_EmailChanging(value);
					this.SendPropertyChanging();
					this._Ope_Email = value;
					this.SendPropertyChanged("Ope_Email");
					this.OnOpe_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_Telefon", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Ope_Telefon
		{
			get
			{
				return this._Ope_Telefon;
			}
			set
			{
				if ((this._Ope_Telefon != value))
				{
					this.OnOpe_TelefonChanging(value);
					this.SendPropertyChanging();
					this._Ope_Telefon = value;
					this.SendPropertyChanged("Ope_Telefon");
					this.OnOpe_TelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_NazwaKomputera", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string Ope_NazwaKomputera
		{
			get
			{
				return this._Ope_NazwaKomputera;
			}
			set
			{
				if ((this._Ope_NazwaKomputera != value))
				{
					this.OnOpe_NazwaKomputeraChanging(value);
					this.SendPropertyChanging();
					this._Ope_NazwaKomputera = value;
					this.SendPropertyChanged("Ope_NazwaKomputera");
					this.OnOpe_NazwaKomputeraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_InfoPoUruchomieniu", DbType="TinyInt NOT NULL")]
		public byte Ope_InfoPoUruchomieniu
		{
			get
			{
				return this._Ope_InfoPoUruchomieniu;
			}
			set
			{
				if ((this._Ope_InfoPoUruchomieniu != value))
				{
					this.OnOpe_InfoPoUruchomieniuChanging(value);
					this.SendPropertyChanging();
					this._Ope_InfoPoUruchomieniu = value;
					this.SendPropertyChanged("Ope_InfoPoUruchomieniu");
					this.OnOpe_InfoPoUruchomieniuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_InfoRazDziennie", DbType="TinyInt NOT NULL")]
		public byte Ope_InfoRazDziennie
		{
			get
			{
				return this._Ope_InfoRazDziennie;
			}
			set
			{
				if ((this._Ope_InfoRazDziennie != value))
				{
					this.OnOpe_InfoRazDziennieChanging(value);
					this.SendPropertyChanging();
					this._Ope_InfoRazDziennie = value;
					this.SendPropertyChanged("Ope_InfoRazDziennie");
					this.OnOpe_InfoRazDziennieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ZmianaLimituKred", DbType="TinyInt NOT NULL")]
		public byte Ope_ZmianaLimituKred
		{
			get
			{
				return this._Ope_ZmianaLimituKred;
			}
			set
			{
				if ((this._Ope_ZmianaLimituKred != value))
				{
					this.OnOpe_ZmianaLimituKredChanging(value);
					this.SendPropertyChanging();
					this._Ope_ZmianaLimituKred = value;
					this.SendPropertyChanged("Ope_ZmianaLimituKred");
					this.OnOpe_ZmianaLimituKredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_PlatnosciSprzedazTrwaly", DbType="TinyInt NOT NULL")]
		public byte Ope_PlatnosciSprzedazTrwaly
		{
			get
			{
				return this._Ope_PlatnosciSprzedazTrwaly;
			}
			set
			{
				if ((this._Ope_PlatnosciSprzedazTrwaly != value))
				{
					this.OnOpe_PlatnosciSprzedazTrwalyChanging(value);
					this.SendPropertyChanging();
					this._Ope_PlatnosciSprzedazTrwaly = value;
					this.SendPropertyChanged("Ope_PlatnosciSprzedazTrwaly");
					this.OnOpe_PlatnosciSprzedazTrwalyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ZmianaAtrNaZatwDok", DbType="TinyInt NOT NULL")]
		public byte Ope_ZmianaAtrNaZatwDok
		{
			get
			{
				return this._Ope_ZmianaAtrNaZatwDok;
			}
			set
			{
				if ((this._Ope_ZmianaAtrNaZatwDok != value))
				{
					this.OnOpe_ZmianaAtrNaZatwDokChanging(value);
					this.SendPropertyChanging();
					this._Ope_ZmianaAtrNaZatwDok = value;
					this.SendPropertyChanged("Ope_ZmianaAtrNaZatwDok");
					this.OnOpe_ZmianaAtrNaZatwDokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_PlatnosciSprzedazBufor", DbType="TinyInt NOT NULL")]
		public byte Ope_PlatnosciSprzedazBufor
		{
			get
			{
				return this._Ope_PlatnosciSprzedazBufor;
			}
			set
			{
				if ((this._Ope_PlatnosciSprzedazBufor != value))
				{
					this.OnOpe_PlatnosciSprzedazBuforChanging(value);
					this.SendPropertyChanging();
					this._Ope_PlatnosciSprzedazBufor = value;
					this.SendPropertyChanged("Ope_PlatnosciSprzedazBufor");
					this.OnOpe_PlatnosciSprzedazBuforChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ZmianaKategorii", DbType="TinyInt NOT NULL")]
		public byte Ope_ZmianaKategorii
		{
			get
			{
				return this._Ope_ZmianaKategorii;
			}
			set
			{
				if ((this._Ope_ZmianaKategorii != value))
				{
					this.OnOpe_ZmianaKategoriiChanging(value);
					this.SendPropertyChanging();
					this._Ope_ZmianaKategorii = value;
					this.SendPropertyChanged("Ope_ZmianaKategorii");
					this.OnOpe_ZmianaKategoriiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_Kierownik", DbType="TinyInt NOT NULL")]
		public byte Ope_Kierownik
		{
			get
			{
				return this._Ope_Kierownik;
			}
			set
			{
				if ((this._Ope_Kierownik != value))
				{
					this.OnOpe_KierownikChanging(value);
					this.SendPropertyChanging();
					this._Ope_Kierownik = value;
					this.SendPropertyChanged("Ope_Kierownik");
					this.OnOpe_KierownikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaZmianTowaru", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaZmianTowaru
		{
			get
			{
				return this._Ope_BlokadaZmianTowaru;
			}
			set
			{
				if ((this._Ope_BlokadaZmianTowaru != value))
				{
					this.OnOpe_BlokadaZmianTowaruChanging(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaZmianTowaru = value;
					this.SendPropertyChanged("Ope_BlokadaZmianTowaru");
					this.OnOpe_BlokadaZmianTowaruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaZmianMagazynu", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaZmianMagazynu
		{
			get
			{
				return this._Ope_BlokadaZmianMagazynu;
			}
			set
			{
				if ((this._Ope_BlokadaZmianMagazynu != value))
				{
					this.OnOpe_BlokadaZmianMagazynuChanging(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaZmianMagazynu = value;
					this.SendPropertyChanged("Ope_BlokadaZmianMagazynu");
					this.OnOpe_BlokadaZmianMagazynuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaZmianMagazynuListy", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaZmianMagazynuListy
		{
			get
			{
				return this._Ope_BlokadaZmianMagazynuListy;
			}
			set
			{
				if ((this._Ope_BlokadaZmianMagazynuListy != value))
				{
					this.OnOpe_BlokadaZmianMagazynuListyChanging(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaZmianMagazynuListy = value;
					this.SendPropertyChanged("Ope_BlokadaZmianMagazynuListy");
					this.OnOpe_BlokadaZmianMagazynuListyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaZmianCenFA", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaZmianCenFA
		{
			get
			{
				return this._Ope_BlokadaZmianCenFA;
			}
			set
			{
				if ((this._Ope_BlokadaZmianCenFA != value))
				{
					this.OnOpe_BlokadaZmianCenFAChanging(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaZmianCenFA = value;
					this.SendPropertyChanged("Ope_BlokadaZmianCenFA");
					this.OnOpe_BlokadaZmianCenFAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaZmianCenFPF", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaZmianCenFPF
		{
			get
			{
				return this._Ope_BlokadaZmianCenFPF;
			}
			set
			{
				if ((this._Ope_BlokadaZmianCenFPF != value))
				{
					this.OnOpe_BlokadaZmianCenFPFChanging(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaZmianCenFPF = value;
					this.SendPropertyChanged("Ope_BlokadaZmianCenFPF");
					this.OnOpe_BlokadaZmianCenFPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaZmianCenPA", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaZmianCenPA
		{
			get
			{
				return this._Ope_BlokadaZmianCenPA;
			}
			set
			{
				if ((this._Ope_BlokadaZmianCenPA != value))
				{
					this.OnOpe_BlokadaZmianCenPAChanging(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaZmianCenPA = value;
					this.SendPropertyChanged("Ope_BlokadaZmianCenPA");
					this.OnOpe_BlokadaZmianCenPAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaZmianCenRO", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaZmianCenRO
		{
			get
			{
				return this._Ope_BlokadaZmianCenRO;
			}
			set
			{
				if ((this._Ope_BlokadaZmianCenRO != value))
				{
					this.OnOpe_BlokadaZmianCenROChanging(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaZmianCenRO = value;
					this.SendPropertyChanged("Ope_BlokadaZmianCenRO");
					this.OnOpe_BlokadaZmianCenROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaZmianCenZD", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaZmianCenZD
		{
			get
			{
				return this._Ope_BlokadaZmianCenZD;
			}
			set
			{
				if ((this._Ope_BlokadaZmianCenZD != value))
				{
					this.OnOpe_BlokadaZmianCenZDChanging(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaZmianCenZD = value;
					this.SendPropertyChanged("Ope_BlokadaZmianCenZD");
					this.OnOpe_BlokadaZmianCenZDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaZmianCenFZ", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaZmianCenFZ
		{
			get
			{
				return this._Ope_BlokadaZmianCenFZ;
			}
			set
			{
				if ((this._Ope_BlokadaZmianCenFZ != value))
				{
					this.OnOpe_BlokadaZmianCenFZChanging(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaZmianCenFZ = value;
					this.SendPropertyChanged("Ope_BlokadaZmianCenFZ");
					this.OnOpe_BlokadaZmianCenFZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaFAPAdoBufora", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaFAPAdoBufora
		{
			get
			{
				return this._Ope_BlokadaFAPAdoBufora;
			}
			set
			{
				if ((this._Ope_BlokadaFAPAdoBufora != value))
				{
					this.OnOpe_BlokadaFAPAdoBuforaChanging(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaFAPAdoBufora = value;
					this.SendPropertyChanged("Ope_BlokadaFAPAdoBufora");
					this.OnOpe_BlokadaFAPAdoBuforaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaPonownejFiskFAPA", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaPonownejFiskFAPA
		{
			get
			{
				return this._Ope_BlokadaPonownejFiskFAPA;
			}
			set
			{
				if ((this._Ope_BlokadaPonownejFiskFAPA != value))
				{
					this.OnOpe_BlokadaPonownejFiskFAPAChanging(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaPonownejFiskFAPA = value;
					this.SendPropertyChanged("Ope_BlokadaPonownejFiskFAPA");
					this.OnOpe_BlokadaPonownejFiskFAPAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ZapisFAPApoWydruku", DbType="TinyInt NOT NULL")]
		public byte Ope_ZapisFAPApoWydruku
		{
			get
			{
				return this._Ope_ZapisFAPApoWydruku;
			}
			set
			{
				if ((this._Ope_ZapisFAPApoWydruku != value))
				{
					this.OnOpe_ZapisFAPApoWydrukuChanging(value);
					this.SendPropertyChanging();
					this._Ope_ZapisFAPApoWydruku = value;
					this.SendPropertyChanged("Ope_ZapisFAPApoWydruku");
					this.OnOpe_ZapisFAPApoWydrukuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ZamkniecieDnia", DbType="TinyInt NOT NULL")]
		public byte Ope_ZamkniecieDnia
		{
			get
			{
				return this._Ope_ZamkniecieDnia;
			}
			set
			{
				if ((this._Ope_ZamkniecieDnia != value))
				{
					this.OnOpe_ZamkniecieDniaChanging(value);
					this.SendPropertyChanging();
					this._Ope_ZamkniecieDnia = value;
					this.SendPropertyChanged("Ope_ZamkniecieDnia");
					this.OnOpe_ZamkniecieDniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_AktualizacjaKntHaMag", DbType="TinyInt NOT NULL")]
		public byte Ope_AktualizacjaKntHaMag
		{
			get
			{
				return this._Ope_AktualizacjaKntHaMag;
			}
			set
			{
				if ((this._Ope_AktualizacjaKntHaMag != value))
				{
					this.OnOpe_AktualizacjaKntHaMagChanging(value);
					this.SendPropertyChanging();
					this._Ope_AktualizacjaKntHaMag = value;
					this.SendPropertyChanged("Ope_AktualizacjaKntHaMag");
					this.OnOpe_AktualizacjaKntHaMagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ZmianaOpisuHaMag", DbType="TinyInt NOT NULL")]
		public byte Ope_ZmianaOpisuHaMag
		{
			get
			{
				return this._Ope_ZmianaOpisuHaMag;
			}
			set
			{
				if ((this._Ope_ZmianaOpisuHaMag != value))
				{
					this.OnOpe_ZmianaOpisuHaMagChanging(value);
					this.SendPropertyChanging();
					this._Ope_ZmianaOpisuHaMag = value;
					this.SendPropertyChanged("Ope_ZmianaOpisuHaMag");
					this.OnOpe_ZmianaOpisuHaMagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_MinMarzaHaMag", DbType="TinyInt NOT NULL")]
		public byte Ope_MinMarzaHaMag
		{
			get
			{
				return this._Ope_MinMarzaHaMag;
			}
			set
			{
				if ((this._Ope_MinMarzaHaMag != value))
				{
					this.OnOpe_MinMarzaHaMagChanging(value);
					this.SendPropertyChanging();
					this._Ope_MinMarzaHaMag = value;
					this.SendPropertyChanged("Ope_MinMarzaHaMag");
					this.OnOpe_MinMarzaHaMagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaAnulowaniaHaMag", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaAnulowaniaHaMag
		{
			get
			{
				return this._Ope_BlokadaAnulowaniaHaMag;
			}
			set
			{
				if ((this._Ope_BlokadaAnulowaniaHaMag != value))
				{
					this.OnOpe_BlokadaAnulowaniaHaMagChanging(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaAnulowaniaHaMag = value;
					this.SendPropertyChanged("Ope_BlokadaAnulowaniaHaMag");
					this.OnOpe_BlokadaAnulowaniaHaMagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_RozliczanieZListyHaMag", DbType="TinyInt NOT NULL")]
		public byte Ope_RozliczanieZListyHaMag
		{
			get
			{
				return this._Ope_RozliczanieZListyHaMag;
			}
			set
			{
				if ((this._Ope_RozliczanieZListyHaMag != value))
				{
					this.OnOpe_RozliczanieZListyHaMagChanging(value);
					this.SendPropertyChanging();
					this._Ope_RozliczanieZListyHaMag = value;
					this.SendPropertyChanged("Ope_RozliczanieZListyHaMag");
					this.OnOpe_RozliczanieZListyHaMagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_SymbolDlaNumeracji", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Ope_SymbolDlaNumeracji
		{
			get
			{
				return this._Ope_SymbolDlaNumeracji;
			}
			set
			{
				if ((this._Ope_SymbolDlaNumeracji != value))
				{
					this.OnOpe_SymbolDlaNumeracjiChanging(value);
					this.SendPropertyChanging();
					this._Ope_SymbolDlaNumeracji = value;
					this.SendPropertyChanged("Ope_SymbolDlaNumeracji");
					this.OnOpe_SymbolDlaNumeracjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_Magazyn", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Ope_Magazyn
		{
			get
			{
				return this._Ope_Magazyn;
			}
			set
			{
				if ((this._Ope_Magazyn != value))
				{
					this.OnOpe_MagazynChanging(value);
					this.SendPropertyChanging();
					this._Ope_Magazyn = value;
					this.SendPropertyChanged("Ope_Magazyn");
					this.OnOpe_MagazynChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_HasloPM", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string Ope_HasloPM
		{
			get
			{
				return this._Ope_HasloPM;
			}
			set
			{
				if ((this._Ope_HasloPM != value))
				{
					this.OnOpe_HasloPMChanging(value);
					this.SendPropertyChanging();
					this._Ope_HasloPM = value;
					this.SendPropertyChanged("Ope_HasloPM");
					this.OnOpe_HasloPMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_Kasa", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Ope_Kasa
		{
			get
			{
				return this._Ope_Kasa;
			}
			set
			{
				if ((this._Ope_Kasa != value))
				{
					this.OnOpe_KasaChanging(value);
					this.SendPropertyChanging();
					this._Ope_Kasa = value;
					this.SendPropertyChanged("Ope_Kasa");
					this.OnOpe_KasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_Bank", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Ope_Bank
		{
			get
			{
				return this._Ope_Bank;
			}
			set
			{
				if ((this._Ope_Bank != value))
				{
					this.OnOpe_BankChanging(value);
					this.SendPropertyChanging();
					this._Ope_Bank = value;
					this.SendPropertyChanged("Ope_Bank");
					this.OnOpe_BankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_Parametr", DbType="NVarChar(254) NOT NULL", CanBeNull=false)]
		public string Ope_Parametr
		{
			get
			{
				return this._Ope_Parametr;
			}
			set
			{
				if ((this._Ope_Parametr != value))
				{
					this.OnOpe_ParametrChanging(value);
					this.SendPropertyChanging();
					this._Ope_Parametr = value;
					this.SendPropertyChanged("Ope_Parametr");
					this.OnOpe_ParametrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_Nieaktywny", DbType="SmallInt NOT NULL")]
		public short Ope_Nieaktywny
		{
			get
			{
				return this._Ope_Nieaktywny;
			}
			set
			{
				if ((this._Ope_Nieaktywny != value))
				{
					this.OnOpe_NieaktywnyChanging(value);
					this.SendPropertyChanging();
					this._Ope_Nieaktywny = value;
					this.SendPropertyChanged("Ope_Nieaktywny");
					this.OnOpe_NieaktywnyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_KodDlaDF", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Ope_KodDlaDF
		{
			get
			{
				return this._Ope_KodDlaDF;
			}
			set
			{
				if ((this._Ope_KodDlaDF != value))
				{
					this.OnOpe_KodDlaDFChanging(value);
					this.SendPropertyChanging();
					this._Ope_KodDlaDF = value;
					this.SendPropertyChanged("Ope_KodDlaDF");
					this.OnOpe_KodDlaDFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_KonfigProgressLoga", DbType="TinyInt NOT NULL")]
		public byte Ope_KonfigProgressLoga
		{
			get
			{
				return this._Ope_KonfigProgressLoga;
			}
			set
			{
				if ((this._Ope_KonfigProgressLoga != value))
				{
					this.OnOpe_KonfigProgressLogaChanging(value);
					this.SendPropertyChanging();
					this._Ope_KonfigProgressLoga = value;
					this.SendPropertyChanged("Ope_KonfigProgressLoga");
					this.OnOpe_KonfigProgressLogaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_RaportProgressLoga", DbType="TinyInt NOT NULL")]
		public byte Ope_RaportProgressLoga
		{
			get
			{
				return this._Ope_RaportProgressLoga;
			}
			set
			{
				if ((this._Ope_RaportProgressLoga != value))
				{
					this.OnOpe_RaportProgressLogaChanging(value);
					this.SendPropertyChanging();
					this._Ope_RaportProgressLoga = value;
					this.SendPropertyChanged("Ope_RaportProgressLoga");
					this.OnOpe_RaportProgressLogaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaPlac", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaPlac
		{
			get
			{
				return this._Ope_BlokadaPlac;
			}
			set
			{
				if ((this._Ope_BlokadaPlac != value))
				{
					this.OnOpe_BlokadaPlacChanging(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaPlac = value;
					this.SendPropertyChanged("Ope_BlokadaPlac");
					this.OnOpe_BlokadaPlacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaTylkoWynagrodzen", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaTylkoWynagrodzen
		{
			get
			{
				return this._Ope_BlokadaTylkoWynagrodzen;
			}
			set
			{
				if ((this._Ope_BlokadaTylkoWynagrodzen != value))
				{
					this.OnOpe_BlokadaTylkoWynagrodzenChanging(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaTylkoWynagrodzen = value;
					this.SendPropertyChanged("Ope_BlokadaTylkoWynagrodzen");
					this.OnOpe_BlokadaTylkoWynagrodzenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ZmianaProcesuDomyslnego", DbType="SmallInt NOT NULL")]
		public short Ope_ZmianaProcesuDomyslnego
		{
			get
			{
				return this._Ope_ZmianaProcesuDomyslnego;
			}
			set
			{
				if ((this._Ope_ZmianaProcesuDomyslnego != value))
				{
					this.OnOpe_ZmianaProcesuDomyslnegoChanging(value);
					this.SendPropertyChanging();
					this._Ope_ZmianaProcesuDomyslnego = value;
					this.SendPropertyChanged("Ope_ZmianaProcesuDomyslnego");
					this.OnOpe_ZmianaProcesuDomyslnegoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ModyfikacjaProcesow", DbType="SmallInt NOT NULL")]
		public short Ope_ModyfikacjaProcesow
		{
			get
			{
				return this._Ope_ModyfikacjaProcesow;
			}
			set
			{
				if ((this._Ope_ModyfikacjaProcesow != value))
				{
					this.OnOpe_ModyfikacjaProcesowChanging(value);
					this.SendPropertyChanging();
					this._Ope_ModyfikacjaProcesow = value;
					this.SendPropertyChanged("Ope_ModyfikacjaProcesow");
					this.OnOpe_ModyfikacjaProcesowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_DostepDoSkrzynkiInnychOperatorow", DbType="SmallInt NOT NULL")]
		public short Ope_DostepDoSkrzynkiInnychOperatorow
		{
			get
			{
				return this._Ope_DostepDoSkrzynkiInnychOperatorow;
			}
			set
			{
				if ((this._Ope_DostepDoSkrzynkiInnychOperatorow != value))
				{
					this.OnOpe_DostepDoSkrzynkiInnychOperatorowChanging(value);
					this.SendPropertyChanging();
					this._Ope_DostepDoSkrzynkiInnychOperatorow = value;
					this.SendPropertyChanged("Ope_DostepDoSkrzynkiInnychOperatorow");
					this.OnOpe_DostepDoSkrzynkiInnychOperatorowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_DostepDoKontInnychOperatorow", DbType="TinyInt NOT NULL")]
		public byte Ope_DostepDoKontInnychOperatorow
		{
			get
			{
				return this._Ope_DostepDoKontInnychOperatorow;
			}
			set
			{
				if ((this._Ope_DostepDoKontInnychOperatorow != value))
				{
					this.OnOpe_DostepDoKontInnychOperatorowChanging(value);
					this.SendPropertyChanging();
					this._Ope_DostepDoKontInnychOperatorow = value;
					this.SendPropertyChanged("Ope_DostepDoKontInnychOperatorow");
					this.OnOpe_DostepDoKontInnychOperatorowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_PrawoOdblokowaniaKontaktu", DbType="SmallInt NOT NULL")]
		public short Ope_PrawoOdblokowaniaKontaktu
		{
			get
			{
				return this._Ope_PrawoOdblokowaniaKontaktu;
			}
			set
			{
				if ((this._Ope_PrawoOdblokowaniaKontaktu != value))
				{
					this.OnOpe_PrawoOdblokowaniaKontaktuChanging(value);
					this.SendPropertyChanging();
					this._Ope_PrawoOdblokowaniaKontaktu = value;
					this.SendPropertyChanged("Ope_PrawoOdblokowaniaKontaktu");
					this.OnOpe_PrawoOdblokowaniaKontaktuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_KopiaBezpieczenstwa", DbType="TinyInt")]
		public System.Nullable<byte> Ope_KopiaBezpieczenstwa
		{
			get
			{
				return this._Ope_KopiaBezpieczenstwa;
			}
			set
			{
				if ((this._Ope_KopiaBezpieczenstwa != value))
				{
					this.OnOpe_KopiaBezpieczenstwaChanging(value);
					this.SendPropertyChanging();
					this._Ope_KopiaBezpieczenstwa = value;
					this.SendPropertyChanged("Ope_KopiaBezpieczenstwa");
					this.OnOpe_KopiaBezpieczenstwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_PrawoDoZamianEFaktury", DbType="SmallInt NOT NULL")]
		public short Ope_PrawoDoZamianEFaktury
		{
			get
			{
				return this._Ope_PrawoDoZamianEFaktury;
			}
			set
			{
				if ((this._Ope_PrawoDoZamianEFaktury != value))
				{
					this.OnOpe_PrawoDoZamianEFakturyChanging(value);
					this.SendPropertyChanging();
					this._Ope_PrawoDoZamianEFaktury = value;
					this.SendPropertyChanged("Ope_PrawoDoZamianEFaktury");
					this.OnOpe_PrawoDoZamianEFakturyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_KotrolaCzesciPobranych", DbType="TinyInt NOT NULL")]
		public byte Ope_KotrolaCzesciPobranych
		{
			get
			{
				return this._Ope_KotrolaCzesciPobranych;
			}
			set
			{
				if ((this._Ope_KotrolaCzesciPobranych != value))
				{
					this.OnOpe_KotrolaCzesciPobranychChanging(value);
					this.SendPropertyChanging();
					this._Ope_KotrolaCzesciPobranych = value;
					this.SendPropertyChanged("Ope_KotrolaCzesciPobranych");
					this.OnOpe_KotrolaCzesciPobranychChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_DetalFunkcjaPrac", DbType="Int NOT NULL")]
		public int Ope_DetalFunkcjaPrac
		{
			get
			{
				return this._Ope_DetalFunkcjaPrac;
			}
			set
			{
				if ((this._Ope_DetalFunkcjaPrac != value))
				{
					this.OnOpe_DetalFunkcjaPracChanging(value);
					this.SendPropertyChanging();
					this._Ope_DetalFunkcjaPrac = value;
					this.SendPropertyChanged("Ope_DetalFunkcjaPrac");
					this.OnOpe_DetalFunkcjaPracChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_UproszczoneFakturowanie", DbType="TinyInt NOT NULL")]
		public byte Ope_UproszczoneFakturowanie
		{
			get
			{
				return this._Ope_UproszczoneFakturowanie;
			}
			set
			{
				if ((this._Ope_UproszczoneFakturowanie != value))
				{
					this.OnOpe_UproszczoneFakturowanieChanging(value);
					this.SendPropertyChanging();
					this._Ope_UproszczoneFakturowanie = value;
					this.SendPropertyChanged("Ope_UproszczoneFakturowanie");
					this.OnOpe_UproszczoneFakturowanieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_PrawoDoPobrCzesciMagSerw", DbType="TinyInt NOT NULL")]
		public byte Ope_PrawoDoPobrCzesciMagSerw
		{
			get
			{
				return this._Ope_PrawoDoPobrCzesciMagSerw;
			}
			set
			{
				if ((this._Ope_PrawoDoPobrCzesciMagSerw != value))
				{
					this.OnOpe_PrawoDoPobrCzesciMagSerwChanging(value);
					this.SendPropertyChanging();
					this._Ope_PrawoDoPobrCzesciMagSerw = value;
					this.SendPropertyChanged("Ope_PrawoDoPobrCzesciMagSerw");
					this.OnOpe_PrawoDoPobrCzesciMagSerwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_PrawoDoPobrCzesciMagLok", DbType="TinyInt NOT NULL")]
		public byte Ope_PrawoDoPobrCzesciMagLok
		{
			get
			{
				return this._Ope_PrawoDoPobrCzesciMagLok;
			}
			set
			{
				if ((this._Ope_PrawoDoPobrCzesciMagLok != value))
				{
					this.OnOpe_PrawoDoPobrCzesciMagLokChanging(value);
					this.SendPropertyChanging();
					this._Ope_PrawoDoPobrCzesciMagLok = value;
					this.SendPropertyChanged("Ope_PrawoDoPobrCzesciMagLok");
					this.OnOpe_PrawoDoPobrCzesciMagLokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_Opis", DbType="NVarChar(254) NOT NULL", CanBeNull=false)]
		public string Ope_Opis
		{
			get
			{
				return this._Ope_Opis;
			}
			set
			{
				if ((this._Ope_Opis != value))
				{
					this.OnOpe_OpisChanging(value);
					this.SendPropertyChanging();
					this._Ope_Opis = value;
					this.SendPropertyChanged("Ope_Opis");
					this.OnOpe_OpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_InfoData", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ope_InfoData
		{
			get
			{
				return this._Ope_InfoData;
			}
			set
			{
				if ((this._Ope_InfoData != value))
				{
					this.OnOpe_InfoDataChanging(value);
					this.SendPropertyChanging();
					this._Ope_InfoData = value;
					this.SendPropertyChanged("Ope_InfoData");
					this.OnOpe_InfoDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_DataZmianyHasla", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ope_DataZmianyHasla
		{
			get
			{
				return this._Ope_DataZmianyHasla;
			}
			set
			{
				if ((this._Ope_DataZmianyHasla != value))
				{
					this.OnOpe_DataZmianyHaslaChanging(value);
					this.SendPropertyChanging();
					this._Ope_DataZmianyHasla = value;
					this.SendPropertyChanged("Ope_DataZmianyHasla");
					this.OnOpe_DataZmianyHaslaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_BlokadaSeryjnegoUsuwania", DbType="TinyInt NOT NULL")]
		public byte Ope_BlokadaSeryjnegoUsuwania
		{
			get
			{
				return this._Ope_BlokadaSeryjnegoUsuwania;
			}
			set
			{
				if ((this._Ope_BlokadaSeryjnegoUsuwania != value))
				{
					this.OnOpe_BlokadaSeryjnegoUsuwaniaChanging(value);
					this.SendPropertyChanging();
					this._Ope_BlokadaSeryjnegoUsuwania = value;
					this.SendPropertyChanged("Ope_BlokadaSeryjnegoUsuwania");
					this.OnOpe_BlokadaSeryjnegoUsuwaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_PrawoDoOdblokowaniaEDeklaracji", DbType="TinyInt NOT NULL")]
		public byte Ope_PrawoDoOdblokowaniaEDeklaracji
		{
			get
			{
				return this._Ope_PrawoDoOdblokowaniaEDeklaracji;
			}
			set
			{
				if ((this._Ope_PrawoDoOdblokowaniaEDeklaracji != value))
				{
					this.OnOpe_PrawoDoOdblokowaniaEDeklaracjiChanging(value);
					this.SendPropertyChanging();
					this._Ope_PrawoDoOdblokowaniaEDeklaracji = value;
					this.SendPropertyChanged("Ope_PrawoDoOdblokowaniaEDeklaracji");
					this.OnOpe_PrawoDoOdblokowaniaEDeklaracjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_DataRSS", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ope_DataRSS
		{
			get
			{
				return this._Ope_DataRSS;
			}
			set
			{
				if ((this._Ope_DataRSS != value))
				{
					this.OnOpe_DataRSSChanging(value);
					this.SendPropertyChanging();
					this._Ope_DataRSS = value;
					this.SendPropertyChanged("Ope_DataRSS");
					this.OnOpe_DataRSSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_PrawoUsuwaniaMaili", DbType="TinyInt NOT NULL")]
		public byte Ope_PrawoUsuwaniaMaili
		{
			get
			{
				return this._Ope_PrawoUsuwaniaMaili;
			}
			set
			{
				if ((this._Ope_PrawoUsuwaniaMaili != value))
				{
					this.OnOpe_PrawoUsuwaniaMailiChanging(value);
					this.SendPropertyChanging();
					this._Ope_PrawoUsuwaniaMaili = value;
					this.SendPropertyChanged("Ope_PrawoUsuwaniaMaili");
					this.OnOpe_PrawoUsuwaniaMailiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_WyswietlajWersje", DbType="TinyInt NOT NULL")]
		public byte Ope_WyswietlajWersje
		{
			get
			{
				return this._Ope_WyswietlajWersje;
			}
			set
			{
				if ((this._Ope_WyswietlajWersje != value))
				{
					this.OnOpe_WyswietlajWersjeChanging(value);
					this.SendPropertyChanging();
					this._Ope_WyswietlajWersje = value;
					this.SendPropertyChanged("Ope_WyswietlajWersje");
					this.OnOpe_WyswietlajWersjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_WyswietlajInformacje", DbType="TinyInt NOT NULL")]
		public byte Ope_WyswietlajInformacje
		{
			get
			{
				return this._Ope_WyswietlajInformacje;
			}
			set
			{
				if ((this._Ope_WyswietlajInformacje != value))
				{
					this.OnOpe_WyswietlajInformacjeChanging(value);
					this.SendPropertyChanging();
					this._Ope_WyswietlajInformacje = value;
					this.SendPropertyChanged("Ope_WyswietlajInformacje");
					this.OnOpe_WyswietlajInformacjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_WyswietlajOferteComarch", DbType="TinyInt NOT NULL")]
		public byte Ope_WyswietlajOferteComarch
		{
			get
			{
				return this._Ope_WyswietlajOferteComarch;
			}
			set
			{
				if ((this._Ope_WyswietlajOferteComarch != value))
				{
					this.OnOpe_WyswietlajOferteComarchChanging(value);
					this.SendPropertyChanging();
					this._Ope_WyswietlajOferteComarch = value;
					this.SendPropertyChanged("Ope_WyswietlajOferteComarch");
					this.OnOpe_WyswietlajOferteComarchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_GIDTyp", DbType="SmallInt")]
		public System.Nullable<short> Ope_GIDTyp
		{
			get
			{
				return this._Ope_GIDTyp;
			}
			set
			{
				if ((this._Ope_GIDTyp != value))
				{
					this.OnOpe_GIDTypChanging(value);
					this.SendPropertyChanging();
					this._Ope_GIDTyp = value;
					this.SendPropertyChanged("Ope_GIDTyp");
					this.OnOpe_GIDTypChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_GIDFirma", DbType="Int")]
		public System.Nullable<int> Ope_GIDFirma
		{
			get
			{
				return this._Ope_GIDFirma;
			}
			set
			{
				if ((this._Ope_GIDFirma != value))
				{
					this.OnOpe_GIDFirmaChanging(value);
					this.SendPropertyChanging();
					this._Ope_GIDFirma = value;
					this.SendPropertyChanged("Ope_GIDFirma");
					this.OnOpe_GIDFirmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_GIDNumer", DbType="Int")]
		public System.Nullable<int> Ope_GIDNumer
		{
			get
			{
				return this._Ope_GIDNumer;
			}
			set
			{
				if ((this._Ope_GIDNumer != value))
				{
					this.OnOpe_GIDNumerChanging(value);
					this.SendPropertyChanging();
					this._Ope_GIDNumer = value;
					this.SendPropertyChanged("Ope_GIDNumer");
					this.OnOpe_GIDNumerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_GIDLp", DbType="SmallInt")]
		public System.Nullable<short> Ope_GIDLp
		{
			get
			{
				return this._Ope_GIDLp;
			}
			set
			{
				if ((this._Ope_GIDLp != value))
				{
					this.OnOpe_GIDLpChanging(value);
					this.SendPropertyChanging();
					this._Ope_GIDLp = value;
					this.SendPropertyChanged("Ope_GIDLp");
					this.OnOpe_GIDLpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_PelneMenu", DbType="TinyInt NOT NULL")]
		public byte Ope_PelneMenu
		{
			get
			{
				return this._Ope_PelneMenu;
			}
			set
			{
				if ((this._Ope_PelneMenu != value))
				{
					this.OnOpe_PelneMenuChanging(value);
					this.SendPropertyChanging();
					this._Ope_PelneMenu = value;
					this.SendPropertyChanged("Ope_PelneMenu");
					this.OnOpe_PelneMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ModulKP", DbType="TinyInt NOT NULL")]
		public byte Ope_ModulKP
		{
			get
			{
				return this._Ope_ModulKP;
			}
			set
			{
				if ((this._Ope_ModulKP != value))
				{
					this.OnOpe_ModulKPChanging(value);
					this.SendPropertyChanging();
					this._Ope_ModulKP = value;
					this.SendPropertyChanged("Ope_ModulKP");
					this.OnOpe_ModulKPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ModulKH", DbType="TinyInt NOT NULL")]
		public byte Ope_ModulKH
		{
			get
			{
				return this._Ope_ModulKH;
			}
			set
			{
				if ((this._Ope_ModulKH != value))
				{
					this.OnOpe_ModulKHChanging(value);
					this.SendPropertyChanging();
					this._Ope_ModulKH = value;
					this.SendPropertyChanged("Ope_ModulKH");
					this.OnOpe_ModulKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ModulST", DbType="TinyInt NOT NULL")]
		public byte Ope_ModulST
		{
			get
			{
				return this._Ope_ModulST;
			}
			set
			{
				if ((this._Ope_ModulST != value))
				{
					this.OnOpe_ModulSTChanging(value);
					this.SendPropertyChanging();
					this._Ope_ModulST = value;
					this.SendPropertyChanged("Ope_ModulST");
					this.OnOpe_ModulSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ModulFA", DbType="TinyInt NOT NULL")]
		public byte Ope_ModulFA
		{
			get
			{
				return this._Ope_ModulFA;
			}
			set
			{
				if ((this._Ope_ModulFA != value))
				{
					this.OnOpe_ModulFAChanging(value);
					this.SendPropertyChanging();
					this._Ope_ModulFA = value;
					this.SendPropertyChanged("Ope_ModulFA");
					this.OnOpe_ModulFAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ModulMAG", DbType="TinyInt NOT NULL")]
		public byte Ope_ModulMAG
		{
			get
			{
				return this._Ope_ModulMAG;
			}
			set
			{
				if ((this._Ope_ModulMAG != value))
				{
					this.OnOpe_ModulMAGChanging(value);
					this.SendPropertyChanging();
					this._Ope_ModulMAG = value;
					this.SendPropertyChanged("Ope_ModulMAG");
					this.OnOpe_ModulMAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ModulPK", DbType="TinyInt NOT NULL")]
		public byte Ope_ModulPK
		{
			get
			{
				return this._Ope_ModulPK;
			}
			set
			{
				if ((this._Ope_ModulPK != value))
				{
					this.OnOpe_ModulPKChanging(value);
					this.SendPropertyChanging();
					this._Ope_ModulPK = value;
					this.SendPropertyChanged("Ope_ModulPK");
					this.OnOpe_ModulPKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ModulPKXL", DbType="TinyInt NOT NULL")]
		public byte Ope_ModulPKXL
		{
			get
			{
				return this._Ope_ModulPKXL;
			}
			set
			{
				if ((this._Ope_ModulPKXL != value))
				{
					this.OnOpe_ModulPKXLChanging(value);
					this.SendPropertyChanging();
					this._Ope_ModulPKXL = value;
					this.SendPropertyChanged("Ope_ModulPKXL");
					this.OnOpe_ModulPKXLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ModulANL", DbType="TinyInt NOT NULL")]
		public byte Ope_ModulANL
		{
			get
			{
				return this._Ope_ModulANL;
			}
			set
			{
				if ((this._Ope_ModulANL != value))
				{
					this.OnOpe_ModulANLChanging(value);
					this.SendPropertyChanging();
					this._Ope_ModulANL = value;
					this.SendPropertyChanged("Ope_ModulANL");
					this.OnOpe_ModulANLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ModulCRM", DbType="TinyInt NOT NULL")]
		public byte Ope_ModulCRM
		{
			get
			{
				return this._Ope_ModulCRM;
			}
			set
			{
				if ((this._Ope_ModulCRM != value))
				{
					this.OnOpe_ModulCRMChanging(value);
					this.SendPropertyChanging();
					this._Ope_ModulCRM = value;
					this.SendPropertyChanged("Ope_ModulCRM");
					this.OnOpe_ModulCRMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ModulCRMP", DbType="TinyInt NOT NULL")]
		public byte Ope_ModulCRMP
		{
			get
			{
				return this._Ope_ModulCRMP;
			}
			set
			{
				if ((this._Ope_ModulCRMP != value))
				{
					this.OnOpe_ModulCRMPChanging(value);
					this.SendPropertyChanging();
					this._Ope_ModulCRMP = value;
					this.SendPropertyChanged("Ope_ModulCRMP");
					this.OnOpe_ModulCRMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ModulKHP", DbType="TinyInt NOT NULL")]
		public byte Ope_ModulKHP
		{
			get
			{
				return this._Ope_ModulKHP;
			}
			set
			{
				if ((this._Ope_ModulKHP != value))
				{
					this.OnOpe_ModulKHPChanging(value);
					this.SendPropertyChanging();
					this._Ope_ModulKHP = value;
					this.SendPropertyChanged("Ope_ModulKHP");
					this.OnOpe_ModulKHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ModulDET", DbType="TinyInt NOT NULL")]
		public byte Ope_ModulDET
		{
			get
			{
				return this._Ope_ModulDET;
			}
			set
			{
				if ((this._Ope_ModulDET != value))
				{
					this.OnOpe_ModulDETChanging(value);
					this.SendPropertyChanging();
					this._Ope_ModulDET = value;
					this.SendPropertyChanged("Ope_ModulDET");
					this.OnOpe_ModulDETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ModulBIU", DbType="TinyInt NOT NULL")]
		public byte Ope_ModulBIU
		{
			get
			{
				return this._Ope_ModulBIU;
			}
			set
			{
				if ((this._Ope_ModulBIU != value))
				{
					this.OnOpe_ModulBIUChanging(value);
					this.SendPropertyChanging();
					this._Ope_ModulBIU = value;
					this.SendPropertyChanged("Ope_ModulBIU");
					this.OnOpe_ModulBIUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ModulSRW", DbType="TinyInt NOT NULL")]
		public byte Ope_ModulSRW
		{
			get
			{
				return this._Ope_ModulSRW;
			}
			set
			{
				if ((this._Ope_ModulSRW != value))
				{
					this.OnOpe_ModulSRWChanging(value);
					this.SendPropertyChanging();
					this._Ope_ModulSRW = value;
					this.SendPropertyChanged("Ope_ModulSRW");
					this.OnOpe_ModulSRWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ModulOBD", DbType="TinyInt NOT NULL")]
		public byte Ope_ModulOBD
		{
			get
			{
				return this._Ope_ModulOBD;
			}
			set
			{
				if ((this._Ope_ModulOBD != value))
				{
					this.OnOpe_ModulOBDChanging(value);
					this.SendPropertyChanging();
					this._Ope_ModulOBD = value;
					this.SendPropertyChanged("Ope_ModulOBD");
					this.OnOpe_ModulOBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ModulKB", DbType="TinyInt NOT NULL")]
		public byte Ope_ModulKB
		{
			get
			{
				return this._Ope_ModulKB;
			}
			set
			{
				if ((this._Ope_ModulKB != value))
				{
					this.OnOpe_ModulKBChanging(value);
					this.SendPropertyChanging();
					this._Ope_ModulKB = value;
					this.SendPropertyChanged("Ope_ModulKB");
					this.OnOpe_ModulKBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ModulKBP", DbType="TinyInt NOT NULL")]
		public byte Ope_ModulKBP
		{
			get
			{
				return this._Ope_ModulKBP;
			}
			set
			{
				if ((this._Ope_ModulKBP != value))
				{
					this.OnOpe_ModulKBPChanging(value);
					this.SendPropertyChanging();
					this._Ope_ModulKBP = value;
					this.SendPropertyChanged("Ope_ModulKBP");
					this.OnOpe_ModulKBPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_ModulHAP", DbType="TinyInt NOT NULL")]
		public byte Ope_ModulHAP
		{
			get
			{
				return this._Ope_ModulHAP;
			}
			set
			{
				if ((this._Ope_ModulHAP != value))
				{
					this.OnOpe_ModulHAPChanging(value);
					this.SendPropertyChanging();
					this._Ope_ModulHAP = value;
					this.SendPropertyChanged("Ope_ModulHAP");
					this.OnOpe_ModulHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_IBard24Login", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Ope_IBard24Login
		{
			get
			{
				return this._Ope_IBard24Login;
			}
			set
			{
				if ((this._Ope_IBard24Login != value))
				{
					this.OnOpe_IBard24LoginChanging(value);
					this.SendPropertyChanging();
					this._Ope_IBard24Login = value;
					this.SendPropertyChanged("Ope_IBard24Login");
					this.OnOpe_IBard24LoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_IBard24Haslo", DbType="NVarChar(1024)")]
		public string Ope_IBard24Haslo
		{
			get
			{
				return this._Ope_IBard24Haslo;
			}
			set
			{
				if ((this._Ope_IBard24Haslo != value))
				{
					this.OnOpe_IBard24HasloChanging(value);
					this.SendPropertyChanging();
					this._Ope_IBard24Haslo = value;
					this.SendPropertyChanged("Ope_IBard24Haslo");
					this.OnOpe_IBard24HasloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_IBard24Wyloguj", DbType="TinyInt NOT NULL")]
		public byte Ope_IBard24Wyloguj
		{
			get
			{
				return this._Ope_IBard24Wyloguj;
			}
			set
			{
				if ((this._Ope_IBard24Wyloguj != value))
				{
					this.OnOpe_IBard24WylogujChanging(value);
					this.SendPropertyChanging();
					this._Ope_IBard24Wyloguj = value;
					this.SendPropertyChanged("Ope_IBard24Wyloguj");
					this.OnOpe_IBard24WylogujChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_UzywaAnalizBI", DbType="TinyInt NOT NULL")]
		public byte Ope_UzywaAnalizBI
		{
			get
			{
				return this._Ope_UzywaAnalizBI;
			}
			set
			{
				if ((this._Ope_UzywaAnalizBI != value))
				{
					this.OnOpe_UzywaAnalizBIChanging(value);
					this.SendPropertyChanging();
					this._Ope_UzywaAnalizBI = value;
					this.SendPropertyChanged("Ope_UzywaAnalizBI");
					this.OnOpe_UzywaAnalizBIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_AnalizyBI_Administrator", DbType="TinyInt NOT NULL")]
		public byte Ope_AnalizyBI_Administrator
		{
			get
			{
				return this._Ope_AnalizyBI_Administrator;
			}
			set
			{
				if ((this._Ope_AnalizyBI_Administrator != value))
				{
					this.OnOpe_AnalizyBI_AdministratorChanging(value);
					this.SendPropertyChanging();
					this._Ope_AnalizyBI_Administrator = value;
					this.SendPropertyChanged("Ope_AnalizyBI_Administrator");
					this.OnOpe_AnalizyBI_AdministratorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_AnalizyBI_Subskrypcje", DbType="TinyInt NOT NULL")]
		public byte Ope_AnalizyBI_Subskrypcje
		{
			get
			{
				return this._Ope_AnalizyBI_Subskrypcje;
			}
			set
			{
				if ((this._Ope_AnalizyBI_Subskrypcje != value))
				{
					this.OnOpe_AnalizyBI_SubskrypcjeChanging(value);
					this.SendPropertyChanging();
					this._Ope_AnalizyBI_Subskrypcje = value;
					this.SendPropertyChanged("Ope_AnalizyBI_Subskrypcje");
					this.OnOpe_AnalizyBI_SubskrypcjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_AnalizyBI_DodawaniePol", DbType="TinyInt NOT NULL")]
		public byte Ope_AnalizyBI_DodawaniePol
		{
			get
			{
				return this._Ope_AnalizyBI_DodawaniePol;
			}
			set
			{
				if ((this._Ope_AnalizyBI_DodawaniePol != value))
				{
					this.OnOpe_AnalizyBI_DodawaniePolChanging(value);
					this.SendPropertyChanging();
					this._Ope_AnalizyBI_DodawaniePol = value;
					this.SendPropertyChanged("Ope_AnalizyBI_DodawaniePol");
					this.OnOpe_AnalizyBI_DodawaniePolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_AnalizyBI_Drukowanie", DbType="TinyInt NOT NULL")]
		public byte Ope_AnalizyBI_Drukowanie
		{
			get
			{
				return this._Ope_AnalizyBI_Drukowanie;
			}
			set
			{
				if ((this._Ope_AnalizyBI_Drukowanie != value))
				{
					this.OnOpe_AnalizyBI_DrukowanieChanging(value);
					this.SendPropertyChanging();
					this._Ope_AnalizyBI_Drukowanie = value;
					this.SendPropertyChanged("Ope_AnalizyBI_Drukowanie");
					this.OnOpe_AnalizyBI_DrukowanieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_AnalizyBI_Eksport", DbType="TinyInt NOT NULL")]
		public byte Ope_AnalizyBI_Eksport
		{
			get
			{
				return this._Ope_AnalizyBI_Eksport;
			}
			set
			{
				if ((this._Ope_AnalizyBI_Eksport != value))
				{
					this.OnOpe_AnalizyBI_EksportChanging(value);
					this.SendPropertyChanging();
					this._Ope_AnalizyBI_Eksport = value;
					this.SendPropertyChanged("Ope_AnalizyBI_Eksport");
					this.OnOpe_AnalizyBI_EksportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_AnalizyBI_ModyfikacjaZapytania", DbType="TinyInt NOT NULL")]
		public byte Ope_AnalizyBI_ModyfikacjaZapytania
		{
			get
			{
				return this._Ope_AnalizyBI_ModyfikacjaZapytania;
			}
			set
			{
				if ((this._Ope_AnalizyBI_ModyfikacjaZapytania != value))
				{
					this.OnOpe_AnalizyBI_ModyfikacjaZapytaniaChanging(value);
					this.SendPropertyChanging();
					this._Ope_AnalizyBI_ModyfikacjaZapytania = value;
					this.SendPropertyChanged("Ope_AnalizyBI_ModyfikacjaZapytania");
					this.OnOpe_AnalizyBI_ModyfikacjaZapytaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_AnalizyBI_ImportRaportu", DbType="TinyInt NOT NULL")]
		public byte Ope_AnalizyBI_ImportRaportu
		{
			get
			{
				return this._Ope_AnalizyBI_ImportRaportu;
			}
			set
			{
				if ((this._Ope_AnalizyBI_ImportRaportu != value))
				{
					this.OnOpe_AnalizyBI_ImportRaportuChanging(value);
					this.SendPropertyChanging();
					this._Ope_AnalizyBI_ImportRaportu = value;
					this.SendPropertyChanged("Ope_AnalizyBI_ImportRaportu");
					this.OnOpe_AnalizyBI_ImportRaportuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ope_AnalizyBI_KontoGMail", DbType="VarChar(254) NOT NULL", CanBeNull=false)]
		public string Ope_AnalizyBI_KontoGMail
		{
			get
			{
				return this._Ope_AnalizyBI_KontoGMail;
			}
			set
			{
				if ((this._Ope_AnalizyBI_KontoGMail != value))
				{
					this.OnOpe_AnalizyBI_KontoGMailChanging(value);
					this.SendPropertyChanging();
					this._Ope_AnalizyBI_KontoGMail = value;
					this.SendPropertyChanged("Ope_AnalizyBI_KontoGMail");
					this.OnOpe_AnalizyBI_KontoGMailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
