//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolEx.Hurt.Sync.ProviderOptima.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kuleros-PC\\;Initial Catalog=CDN_Demo;Integrated Security=True")]
        public string CDN_DemoConnectionString {
            get {
                return ((string)(this["CDN_DemoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kuleros-pc;Initial Catalog=CDN_Local;Integrated Security=True")]
        public string CDN_LocalConnectionString {
            get {
                return ((string)(this["CDN_LocalConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kuleros-pc;Initial Catalog=CDN_Konfiguracja;Integrated Security=True")]
        public string CDN_KonfiguracjaConnectionString {
            get {
                return ((string)(this["CDN_KonfiguracjaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KULEROS-PC\\sqlserver2008;Initial Catalog=CDN_LEMIR_B2B;Integrated Sec" +
            "urity=True")]
        public string CDN_LEMIR_B2BConnectionString {
            get {
                return ((string)(this["CDN_LEMIR_B2BConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SOLEX;Initial Catalog=cdn_demo;Integrated Security=True")]
        public string cdn_demoConnectionString1 {
            get {
                return ((string)(this["cdn_demoConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex;Initial Catalog=CDN_demo3;Integrated Security=True")]
        public string CDN_demo3ConnectionString {
            get {
                return ((string)(this["CDN_demo3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=7.176.204.120\\CDN_OPTIMA;Initial Catalog=CDN_AMPBIKE;User ID=sa")]
        public string CDN_AMPBIKEConnectionString {
            get {
                return ((string)(this["CDN_AMPBIKEConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=CDN_KNF_Konfiguracja;Integrated Security=Tr" +
            "ue")]
        public string CDN_KNF_KonfiguracjaConnectionString {
            get {
                return ((string)(this["CDN_KNF_KonfiguracjaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=CDN_TESTOWA;Integrated Security=True")]
        public string CDN_TESTOWAConnectionString {
            get {
                return ((string)(this["CDN_TESTOWAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=CDN_TEST2015;Integrated Security=True")]
        public string CDN_TEST2015ConnectionString {
            get {
                return ((string)(this["CDN_TEST2015ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MILO-BIURO\\OPTIMA;Initial Catalog=CDN_MIL__D_FRASUNKIEWICZ;Persist Se" +
            "curity Info=True;User ID=sa;Password=milo.8228282$%")]
        public string CDN_MIL__D_FRASUNKIEWICZConnectionString {
            get {
                return ((string)(this["CDN_MIL__D_FRASUNKIEWICZConnectionString"]));
            }
        }
    }
}
