//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolEx.Hurt.Sync.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KULEROS-PC\\SQLSERVER2008;Initial Catalog=SolEx_Hurt;Integrated Securi" +
            "ty=True")]
        public string SolEx_HurtConnectionString {
            get {
                return ((string)(this["SolEx_HurtConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KULEROS-PC\\SQLSERVER2008;Initial Catalog=B2B_WheelTrade;Integrated Se" +
            "curity=True")]
        public string B2B_WheelTradeConnectionString {
            get {
                return ((string)(this["B2B_WheelTradeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex.net.pl;Initial Catalog=b2b-kolter;Integrated Security=True")]
        public string b2b_kolterConnectionString {
            get {
                return ((string)(this["b2b_kolterConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KULEROS-PC\\SQLSERVER2008;Initial Catalog=B2BAmpbike;Integrated Securi" +
            "ty=True")]
        public string B2BAmpbikeConnectionString {
            get {
                return ((string)(this["B2BAmpbikeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANNAKOMP;Initial Catalog=b2b-kolter;Integrated Security=True")]
        public string b2b_kolterConnectionString1 {
            get {
                return ((string)(this["b2b_kolterConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex.net.pl;Initial Catalog=b2b-borbet;Integrated Security=True")]
        public string b2b_borbetConnectionString {
            get {
                return ((string)(this["b2b_borbetConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex.net.pl;Initial Catalog=b2b-opoczno;Integrated Security=True")]
        public string b2b_opocznoConnectionString {
            get {
                return ((string)(this["b2b_opocznoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex.net.pl;Initial Catalog=b2b-exec2;Integrated Security=True")]
        public string b2b_exec2ConnectionString {
            get {
                return ((string)(this["b2b_exec2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex.net.pl;Initial Catalog=b2b-norma;Integrated Security=True")]
        public string b2b_normaConnectionString {
            get {
                return ((string)(this["b2b_normaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex.net.pl;Initial Catalog=b2b-print3;Integrated Security=True")]
        public string b2b_print3ConnectionString {
            get {
                return ((string)(this["b2b_print3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=178.33.51.128;Initial Catalog=b2b-print3;Integrated Security=True")]
        public string b2b_print3ConnectionString1 {
            get {
                return ((string)(this["b2b_print3ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=178.33.51.128;Initial Catalog=b2b-essa;Integrated Security=True")]
        public string b2b_essaConnectionString {
            get {
                return ((string)(this["b2b_essaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=178.33.51.128;Initial Catalog=b2b-megima;Integrated Security=True")]
        public string b2b_megimaConnectionString {
            get {
                return ((string)(this["b2b_megimaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-megima;Integrated Security=True")]
        public string b2b_megimaConnectionString1 {
            get {
                return ((string)(this["b2b_megimaConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-essa;Integrated Security=True")]
        public string b2b_essaConnectionString1 {
            get {
                return ((string)(this["b2b_essaConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-ampbike;Integrated Security=True")]
        public string b2b_ampbikeConnectionString {
            get {
                return ((string)(this["b2b_ampbikeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-techmet;Integrated Security=True")]
        public string b2b_techmetConnectionString {
            get {
                return ((string)(this["b2b_techmetConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-variant;Integrated Security=True")]
        public string b2b_variantConnectionString {
            get {
                return ((string)(this["b2b_variantConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=87.204.181.7\\GB;Initial Catalog=b2b-global;Persist Security Info=True" +
            ";User ID=gb_user;Password=GB123baza")]
        public string b2b_globalConnectionString {
            get {
                return ((string)(this["b2b_globalConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-forcetop2;Integrated Security=True" +
            "")]
        public string b2b_forcetop2ConnectionString {
            get {
                return ((string)(this["b2b_forcetop2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.solexb2b.pl;Initial Catalog=b2b-variant2;Integrated Security=True")]
        public string b2b_variant2ConnectionString {
            get {
                return ((string)(this["b2b_variant2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=solex;Initial Catalog=b2b-solex;Integrated Security=True")]
        public string b2b_solexConnectionString {
            get {
                return ((string)(this["b2b_solexConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Solex;Initial Catalog=b2b-solex-branchMateusz;Integrated Security=Tru" +
            "e")]
        public string b2b_solex_branchMateuszConnectionString {
            get {
                return ((string)(this["b2b_solex_branchMateuszConnectionString"]));
            }
        }
    }
}
