using Xunit;
using System.Collections.Generic;
using FakeItEasy;
using SolEx.Hurt.Core.BLL;
using SolEx.Hurt.Core.Importy.Model;
using SolEx.Hurt.Core.ModelBLL;
using SolEx.Hurt.Model;
using SolEx.Hurt.Model.Helpers;
using SolEx.Hurt.Model.Web;

namespace SolEx.Hurt.Core.Importy.Koszyk.Tests
{
    public class OptimaXmlTests
    {
        [Fact()]
        public void PrzetworzTest()
        {
            string dane = @"<ROOT>  
    <DOKUMENT>
		<NAGLOWEK>
			<GENERATOR>Comarch Opt!ma</GENERATOR><TYP_DOKUMENTU>309</TYP_DOKUMENTU><RODZAJ_DOKUMENTU>309000</RODZAJ_DOKUMENTU><FV_MARZA>0</FV_MARZA><FV_MARZA_RODZAJ>0</FV_MARZA_RODZAJ><NUMER_PELNY>ZD/81/12/2016</NUMER_PELNY><DATA_DOKUMENTU>2016-12-20</DATA_DOKUMENTU><DATA_WYSTAWIENIA>2016-12-20</DATA_WYSTAWIENIA><DATA_OPERACJI>2016-12-20</DATA_OPERACJI><TERMIN_ZWROTU_KAUCJI>2017-02-18</TERMIN_ZWROTU_KAUCJI><KOREKTA>0</KOREKTA>
			<DETAL>0</DETAL><TYP_NETTO_BRUTTO>1</TYP_NETTO_BRUTTO><RABAT>0.00</RABAT><OPIS>Dok.: ZD/81/12/2016 (Zamówienie dostawcy)</OPIS>
			<PLATNIK><KOD>BIOPLANET</KOD><NIP>5862160738</NIP><GLN/><NAZWA>BIO PLANET S.A.</NAZWA><ADRES><KOD_POCZTOWY>05-084</KOD_POCZTOWY><MIASTO>Wilkowa Wieś 7</MIASTO><ULICA>Wilkowa Wieś 7</ULICA><KRAJ>Polska</KRAJ></ADRES></PLATNIK>
			<ODBIORCA><KOD>BIOPLANET</KOD><NIP>5862160738</NIP><GLN/><NAZWA>BIO PLANET S.A.</NAZWA><ADRES><KOD_POCZTOWY>05-084</KOD_POCZTOWY><MIASTO>Wilkowa Wieś 7</MIASTO><ULICA>Wilkowa Wieś 7</ULICA><KRAJ>Polska</KRAJ></ADRES></ODBIORCA>
			<SPRZEDAWCA><NIP>957-056-68-61</NIP><GLN>0000000000000</GLN><NAZWA>Kozłek Danuta Broniarek-Zamrzycka</NAZWA><ADRES><KOD_POCZTOWY>80-464</KOD_POCZTOWY><MIASTO>Gdańsk</MIASTO><ULICA>Kombatantów 4</ULICA><KRAJ>Polska</KRAJ></ADRES><NUMER_KONTA_BANKOWEGO>40 1160 2202 0000 0000 8655 0080</NUMER_KONTA_BANKOWEGO><NAZWA_BANKU> Millennium - Centrum Rozliczeniowe</NAZWA_BANKU></SPRZEDAWCA>
			<KATEGORIA><KOD/><OPIS/></KATEGORIA><PLATNOSC><FORMA>przelew</FORMA><TERMIN>2017-01-10</TERMIN></PLATNOSC>
			<WALUTA><SYMBOL>PLN</SYMBOL><KURS_L>1.00</KURS_L><KURS_M>1</KURS_M><PLAT_WAL_OD_PLN>0</PLAT_WAL_OD_PLN><KURS_NUMER>2</KURS_NUMER><KURS_DATA>2016-12-20</KURS_DATA></WALUTA>
			<KWOTY><RAZEM_NETTO_WAL>1531.76</RAZEM_NETTO_WAL><RAZEM_NETTO>1531.76</RAZEM_NETTO><RAZEM_BRUTTO>1619.80</RAZEM_BRUTTO><RAZEM_VAT>88.04</RAZEM_VAT></KWOTY>
			<MAGAZYN_ZRODLOWY>SKLEP</MAGAZYN_ZRODLOWY><MAGAZYN_DOCELOWY/><KAUCJE_PLATNOSCI>0</KAUCJE_PLATNOSCI><BLOKADA_PLATNOSCI>1</BLOKADA_PLATNOSCI><VAT_DLA_DOK_WAL>0</VAT_DLA_DOK_WAL><TRYB_NETTO_VAT>0</TRYB_NETTO_VAT>
		</NAGLOWEK>
		<POZYCJE>
			<POZYCJA><LP>1</LP>
				<TOWAR>
					<KOD>104203</KOD>
					<NAZWA>Bio Planet: chipsy jabłkowe Biominki BIO - 30 g</NAZWA>
					<OPIS/>
					<EAN>5902448165073</EAN>
					<SWW/>
					<NUMER_KATALOGOWY>OP5118</NUMER_KATALOGOWY>
				</TOWAR>
                <STAWKA_VAT><STAWKA>8.00</STAWKA><FLAGA>2</FLAGA><ZRODLOWA>0.00</ZRODLOWA></STAWKA_VAT>
				<CENY><POCZATKOWA_WAL_CENNIKA>2.35</POCZATKOWA_WAL_CENNIKA><POCZATKOWA_WAL_DOKUMENTU>2.35</POCZATKOWA_WAL_DOKUMENTU><PO_RABACIE_WAL_CENNIKA>2.35</PO_RABACIE_WAL_CENNIKA><PO_RABACIE_PLN>2.35</PO_RABACIE_PLN><PO_RABACIE_WAL_DOKUMENTU>2.35</PO_RABACIE_WAL_DOKUMENTU></CENY>
				<WALUTA><SYMBOL>PLN</SYMBOL><KURS_L>1.00</KURS_L><KURS_M>1</KURS_M></WALUTA>
				<RABAT>0.00</RABAT><WARTOSC_NETTO>4.70</WARTOSC_NETTO><WARTOSC_BRUTTO>5.08</WARTOSC_BRUTTO><WARTOSC_NETTO_WAL>4.70</WARTOSC_NETTO_WAL><WARTOSC_BRUTTO_WAL>5.08</WARTOSC_BRUTTO_WAL><ILOSC>              2.0000</ILOSC>
				<JM>SZT</JM><JM_CALKOWITE>0.00</JM_CALKOWITE><JM_ZLOZONA><JMZ>SZT</JMZ><JM_PRZELICZNIK_L>1.00</JM_PRZELICZNIK_L><JM_PRZELICZNIK_M>1</JM_PRZELICZNIK_M></JM_ZLOZONA>
			</POZYCJA>
            <POZYCJA><LP>2</LP>
				<TOWAR>
					<KOD>101325</KOD>
					<NAZWA>Bio Planet: kasza jęczmienna BIO - 500 g</NAZWA>
					<OPIS/>
					<EAN>5907814663733</EAN>
					<SWW/>
					<NUMER_KATALOGOWY>OP2248</NUMER_KATALOGOWY>
				</TOWAR>
				<STAWKA_VAT><STAWKA>5.00</STAWKA><FLAGA>2</FLAGA><ZRODLOWA>0.00</ZRODLOWA></STAWKA_VAT>
				<CENY><POCZATKOWA_WAL_CENNIKA>2.92</POCZATKOWA_WAL_CENNIKA><POCZATKOWA_WAL_DOKUMENTU>2.92</POCZATKOWA_WAL_DOKUMENTU><PO_RABACIE_WAL_CENNIKA>2.92</PO_RABACIE_WAL_CENNIKA><PO_RABACIE_PLN>2.92</PO_RABACIE_PLN><PO_RABACIE_WAL_DOKUMENTU>2.92</PO_RABACIE_WAL_DOKUMENTU></CENY>
				<WALUTA><SYMBOL>PLN</SYMBOL><KURS_L>1.00</KURS_L><KURS_M>1</KURS_M></WALUTA>
				<RABAT>0.00</RABAT><WARTOSC_NETTO>2.92</WARTOSC_NETTO><WARTOSC_BRUTTO>3.07</WARTOSC_BRUTTO><WARTOSC_NETTO_WAL>2.92</WARTOSC_NETTO_WAL><WARTOSC_BRUTTO_WAL>3.07</WARTOSC_BRUTTO_WAL>
				<ILOSC>              1.0000</ILOSC>
				<JM>SZT</JM><JM_CALKOWITE>0.00</JM_CALKOWITE><JM_ZLOZONA><JMZ>SZT</JMZ><JM_PRZELICZNIK_L>1.00</JM_PRZELICZNIK_L><JM_PRZELICZNIK_M>1</JM_PRZELICZNIK_M></JM_ZLOZONA>
			</POZYCJA> 
            <POZYCJA><LP>3</LP>
				<TOWAR>
					<KOD>12301325</KOD>
					<NAZWA>Bio Planet: kasza jęczmienna BIO - 500 g</NAZWA>
					<OPIS/>
					<EAN>590781ewe4663733</EAN>
					<SWW/>
					<NUMER_KATALOGOWY>OP2248</NUMER_KATALOGOWY>
				</TOWAR>
				<STAWKA_VAT><STAWKA>5.00</STAWKA><FLAGA>2</FLAGA><ZRODLOWA>0.00</ZRODLOWA></STAWKA_VAT>
				<CENY><POCZATKOWA_WAL_CENNIKA>2.92</POCZATKOWA_WAL_CENNIKA><POCZATKOWA_WAL_DOKUMENTU>2.92</POCZATKOWA_WAL_DOKUMENTU><PO_RABACIE_WAL_CENNIKA>2.92</PO_RABACIE_WAL_CENNIKA><PO_RABACIE_PLN>2.92</PO_RABACIE_PLN><PO_RABACIE_WAL_DOKUMENTU>2.92</PO_RABACIE_WAL_DOKUMENTU></CENY>
				<WALUTA><SYMBOL>PLN</SYMBOL><KURS_L>1.00</KURS_L><KURS_M>1</KURS_M></WALUTA>
				<RABAT>0.00</RABAT><WARTOSC_NETTO>2.92</WARTOSC_NETTO><WARTOSC_BRUTTO>3.07</WARTOSC_BRUTTO><WARTOSC_NETTO_WAL>2.92</WARTOSC_NETTO_WAL><WARTOSC_BRUTTO_WAL>3.07</WARTOSC_BRUTTO_WAL>
				<ILOSC>              1.0000</ILOSC>
				<JM>SZT</JM><JM_CALKOWITE>0.00</JM_CALKOWITE><JM_ZLOZONA><JMZ>SZT</JMZ><JM_PRZELICZNIK_L>1.00</JM_PRZELICZNIK_L><JM_PRZELICZNIK_M>1</JM_PRZELICZNIK_M></JM_ZLOZONA>
			</POZYCJA>
		</POZYCJE>
        <KAUCJE/><PLATNOSCI/><PLATNOSCI_KAUCJE/>
		<TABELKA_VAT>
			<LINIA_VAT><STAWKA_VAT><STAWKA>5.00</STAWKA><FLAGA>2</FLAGA><ZRODLOWA>0.00</ZRODLOWA></STAWKA_VAT><NETTO>1218.18</NETTO><VAT>60.91</VAT><BRUTTO>1279.09</BRUTTO><NETTO_WAL>1218.18</NETTO_WAL><VAT_WAL>60.91</VAT_WAL><BRUTTO_WAL>1279.09</BRUTTO_WAL></LINIA_VAT>
			<LINIA_VAT><STAWKA_VAT><STAWKA>8.00</STAWKA><FLAGA>2</FLAGA><ZRODLOWA>0.00</ZRODLOWA></STAWKA_VAT><NETTO>299.95</NETTO><VAT>24.00</VAT><BRUTTO>323.95</BRUTTO><NETTO_WAL>299.95</NETTO_WAL><VAT_WAL>24.00</VAT_WAL><BRUTTO_WAL>323.95</BRUTTO_WAL></LINIA_VAT>
			<LINIA_VAT><STAWKA_VAT><STAWKA>23.00</STAWKA><FLAGA>2</FLAGA><ZRODLOWA>0.00</ZRODLOWA></STAWKA_VAT><NETTO>13.63</NETTO><VAT>3.13</VAT><BRUTTO>16.76</BRUTTO><NETTO_WAL>13.63</NETTO_WAL><VAT_WAL>3.13</VAT_WAL><BRUTTO_WAL>16.76</BRUTTO_WAL></LINIA_VAT>
		</TABELKA_VAT>
		<ATRYBUTY/>
	</DOKUMENT>
</ROOT>";

            List<Komunikat> bledy;
            OptimaXml import = new OptimaXml();
            ProduktBazowy pb1 = A.Fake<ProduktBazowy>();
            pb1.KodKreskowy = "5902448165073";
            pb1.Id=1;
            ProduktBazowy pb2 = A.Fake<ProduktBazowy>();
            pb2.KodKreskowy = "5907814663733";
            pb2.Id = 2;

            Jednostka jednostkaProd = new Jednostka();
            jednostkaProd.Nazwa = "SZT";
            jednostkaProd.Id = jednostkaProd.Nazwa.WygenerujIDObiektu();
            Jednostka jednostkaProd2 = new Jednostka();
            jednostkaProd2.Nazwa = "OPAK.";
            jednostkaProd2.Id = jednostkaProd2.Nazwa.WygenerujIDObiektu();
            List<JednostkaProduktu> listaJed = new List<JednostkaProduktu>() {new JednostkaProduktu(jednostkaProd), new JednostkaProduktu(jednostkaProd2)};
            A.CallTo(() => pb1.Jednostki).Returns(listaJed);
            A.CallTo(() => pb2.Jednostki).Returns(listaJed);
            List<ProduktBazowy> produkt1 = new List<ProduktBazowy>() {pb1};
            List<ProduktBazowy> produkt2 = new List<ProduktBazowy>() {pb2};
            ISolexBllCalosc calosc = A.Fake<ISolexBllCalosc>();
            A.CallTo(() => calosc.ProduktyBazowe.ZnajdzProdukty("5902448165073", A<int?>.Ignored)).Returns(produkt1);
            A.CallTo(() => calosc.ProduktyBazowe.ZnajdzProdukty("5907814663733", A<int?>.Ignored)).Returns(produkt2);

            import.Calosc = calosc;

            List<PozycjaKoszykaImportowana> wynik = import.Przetworz(dane, out bledy, null);

            Assert.True(wynik.Count==2, "Czy poprawna ilość");
            Assert.True(bledy.Count == 1, "Czy poprawna ilość błędów");
        }
    }
}